//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddonProcurement.SI_StockMove_EINVServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:scg.co.th:CBMR:EINVENTORY:STOCK", ConfigurationName="SI_StockMove_EINVServiceReference.SI_StockMove")]
    public interface SI_StockMove {
        
        // CODEGEN: Generating message contract since the operation SI_StockMove is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AddonProcurement.SI_StockMove_EINVServiceReference.SI_StockMoveResponse SI_StockMove(AddonProcurement.SI_StockMove_EINVServiceReference.SI_StockMoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<AddonProcurement.SI_StockMove_EINVServiceReference.SI_StockMoveResponse> SI_StockMoveAsync(AddonProcurement.SI_StockMove_EINVServiceReference.SI_StockMoveRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:scg.co.th:CBMR:EINVENTORY:STOCK")]
    public partial class DT_StockMove : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_StockMoveHeader headerField;
        
        private DT_StockMoveItem[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_StockMoveHeader Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("Header");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_StockMoveItem[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:CBMR:EINVENTORY:STOCK")]
    public partial class DT_StockMoveHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pSTNG_DATEField;
        
        private string dOC_DATEField;
        
        private string rEF_DOC_NOField;
        
        private string bILL_OF_LADINGField;
        
        private string gR_GI_SLIP_NOField;
        
        private string hEADER_TXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PSTNG_DATE {
            get {
                return this.pSTNG_DATEField;
            }
            set {
                this.pSTNG_DATEField = value;
                this.RaisePropertyChanged("PSTNG_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DOC_DATE {
            get {
                return this.dOC_DATEField;
            }
            set {
                this.dOC_DATEField = value;
                this.RaisePropertyChanged("DOC_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string REF_DOC_NO {
            get {
                return this.rEF_DOC_NOField;
            }
            set {
                this.rEF_DOC_NOField = value;
                this.RaisePropertyChanged("REF_DOC_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BILL_OF_LADING {
            get {
                return this.bILL_OF_LADINGField;
            }
            set {
                this.bILL_OF_LADINGField = value;
                this.RaisePropertyChanged("BILL_OF_LADING");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string GR_GI_SLIP_NO {
            get {
                return this.gR_GI_SLIP_NOField;
            }
            set {
                this.gR_GI_SLIP_NOField = value;
                this.RaisePropertyChanged("GR_GI_SLIP_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string HEADER_TXT {
            get {
                return this.hEADER_TXTField;
            }
            set {
                this.hEADER_TXTField = value;
                this.RaisePropertyChanged("HEADER_TXT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:scg.co.th:CBMR:EINVENTORY:STOCK")]
    public partial class DT_Return : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_ReturnReturn returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_ReturnReturn Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("Return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:CBMR:EINVENTORY:STOCK")]
    public partial class DT_ReturnReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        private string mBLNRField;
        
        private string mJAHRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MBLNR {
            get {
                return this.mBLNRField;
            }
            set {
                this.mBLNRField = value;
                this.RaisePropertyChanged("MBLNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MJAHR {
            get {
                return this.mJAHRField;
            }
            set {
                this.mJAHRField = value;
                this.RaisePropertyChanged("MJAHR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:CBMR:EINVENTORY:STOCK")]
    public partial class DT_StockMoveItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mATERIALField;
        
        private string pLANTField;
        
        private string sTGE_LOCField;
        
        private string bATCHField;
        
        private string mOVE_TYPEField;
        
        private string eNTRY_QNTField;
        
        private string eNTRY_UOMField;
        
        private string mATERIAL_DESTField;
        
        private string pLANT_DESTField;
        
        private string sLOC_DESTField;
        
        private string cUSTOMERField;
        
        private string kOSTLField;
        
        private string aUFNRField;
        
        private string kONTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
                this.RaisePropertyChanged("MATERIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PLANT {
            get {
                return this.pLANTField;
            }
            set {
                this.pLANTField = value;
                this.RaisePropertyChanged("PLANT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string STGE_LOC {
            get {
                return this.sTGE_LOCField;
            }
            set {
                this.sTGE_LOCField = value;
                this.RaisePropertyChanged("STGE_LOC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BATCH {
            get {
                return this.bATCHField;
            }
            set {
                this.bATCHField = value;
                this.RaisePropertyChanged("BATCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MOVE_TYPE {
            get {
                return this.mOVE_TYPEField;
            }
            set {
                this.mOVE_TYPEField = value;
                this.RaisePropertyChanged("MOVE_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ENTRY_QNT {
            get {
                return this.eNTRY_QNTField;
            }
            set {
                this.eNTRY_QNTField = value;
                this.RaisePropertyChanged("ENTRY_QNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ENTRY_UOM {
            get {
                return this.eNTRY_UOMField;
            }
            set {
                this.eNTRY_UOMField = value;
                this.RaisePropertyChanged("ENTRY_UOM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MATERIAL_DEST {
            get {
                return this.mATERIAL_DESTField;
            }
            set {
                this.mATERIAL_DESTField = value;
                this.RaisePropertyChanged("MATERIAL_DEST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string PLANT_DEST {
            get {
                return this.pLANT_DESTField;
            }
            set {
                this.pLANT_DESTField = value;
                this.RaisePropertyChanged("PLANT_DEST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string SLOC_DEST {
            get {
                return this.sLOC_DESTField;
            }
            set {
                this.sLOC_DESTField = value;
                this.RaisePropertyChanged("SLOC_DEST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string CUSTOMER {
            get {
                return this.cUSTOMERField;
            }
            set {
                this.cUSTOMERField = value;
                this.RaisePropertyChanged("CUSTOMER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string KOSTL {
            get {
                return this.kOSTLField;
            }
            set {
                this.kOSTLField = value;
                this.RaisePropertyChanged("KOSTL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string AUFNR {
            get {
                return this.aUFNRField;
            }
            set {
                this.aUFNRField = value;
                this.RaisePropertyChanged("AUFNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string KONTO {
            get {
                return this.kONTOField;
            }
            set {
                this.kONTOField = value;
                this.RaisePropertyChanged("KONTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_StockMoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:scg.co.th:CBMR:EINVENTORY:STOCK", Order=0)]
        public AddonProcurement.SI_StockMove_EINVServiceReference.DT_StockMove MT_StockMove;
        
        public SI_StockMoveRequest() {
        }
        
        public SI_StockMoveRequest(AddonProcurement.SI_StockMove_EINVServiceReference.DT_StockMove MT_StockMove) {
            this.MT_StockMove = MT_StockMove;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_StockMoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:scg.co.th:CBMR:EINVENTORY:STOCK", Order=0)]
        public AddonProcurement.SI_StockMove_EINVServiceReference.DT_Return MT_Return;
        
        public SI_StockMoveResponse() {
        }
        
        public SI_StockMoveResponse(AddonProcurement.SI_StockMove_EINVServiceReference.DT_Return MT_Return) {
            this.MT_Return = MT_Return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_StockMoveChannel : AddonProcurement.SI_StockMove_EINVServiceReference.SI_StockMove, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_StockMoveClient : System.ServiceModel.ClientBase<AddonProcurement.SI_StockMove_EINVServiceReference.SI_StockMove>, AddonProcurement.SI_StockMove_EINVServiceReference.SI_StockMove {
        
        public SI_StockMoveClient() {
        }
        
        public SI_StockMoveClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_StockMoveClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_StockMoveClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_StockMoveClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AddonProcurement.SI_StockMove_EINVServiceReference.SI_StockMoveResponse AddonProcurement.SI_StockMove_EINVServiceReference.SI_StockMove.SI_StockMove(AddonProcurement.SI_StockMove_EINVServiceReference.SI_StockMoveRequest request) {
            return base.Channel.SI_StockMove(request);
        }
        
        public AddonProcurement.SI_StockMove_EINVServiceReference.DT_Return SI_StockMove(AddonProcurement.SI_StockMove_EINVServiceReference.DT_StockMove MT_StockMove) {
            AddonProcurement.SI_StockMove_EINVServiceReference.SI_StockMoveRequest inValue = new AddonProcurement.SI_StockMove_EINVServiceReference.SI_StockMoveRequest();
            inValue.MT_StockMove = MT_StockMove;
            AddonProcurement.SI_StockMove_EINVServiceReference.SI_StockMoveResponse retVal = ((AddonProcurement.SI_StockMove_EINVServiceReference.SI_StockMove)(this)).SI_StockMove(inValue);
            return retVal.MT_Return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AddonProcurement.SI_StockMove_EINVServiceReference.SI_StockMoveResponse> AddonProcurement.SI_StockMove_EINVServiceReference.SI_StockMove.SI_StockMoveAsync(AddonProcurement.SI_StockMove_EINVServiceReference.SI_StockMoveRequest request) {
            return base.Channel.SI_StockMoveAsync(request);
        }
        
        public System.Threading.Tasks.Task<AddonProcurement.SI_StockMove_EINVServiceReference.SI_StockMoveResponse> SI_StockMoveAsync(AddonProcurement.SI_StockMove_EINVServiceReference.DT_StockMove MT_StockMove) {
            AddonProcurement.SI_StockMove_EINVServiceReference.SI_StockMoveRequest inValue = new AddonProcurement.SI_StockMove_EINVServiceReference.SI_StockMoveRequest();
            inValue.MT_StockMove = MT_StockMove;
            return ((AddonProcurement.SI_StockMove_EINVServiceReference.SI_StockMove)(this)).SI_StockMoveAsync(inValue);
        }
    }
}
