//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddonProcurement.SI_RefPO_EPURServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:scg.co.th:CBMR:EPURCHASING:STOCK", ConfigurationName="SI_RefPO_EPURServiceReference.SI_RefPO")]
    public interface SI_RefPO {
        
        // CODEGEN: Generating message contract since the operation SI_RefPO is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AddonProcurement.SI_RefPO_EPURServiceReference.SI_RefPOResponse SI_RefPO(AddonProcurement.SI_RefPO_EPURServiceReference.SI_RefPORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<AddonProcurement.SI_RefPO_EPURServiceReference.SI_RefPOResponse> SI_RefPOAsync(AddonProcurement.SI_RefPO_EPURServiceReference.SI_RefPORequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:scg.co.th:CBMR:EPURCHASING:STOCK")]
    public partial class DT_RefPO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_RefPOHeader headerField;
        
        private DT_RefPOItem[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_RefPOHeader Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("Header");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_RefPOItem[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:CBMR:EPURCHASING:STOCK")]
    public partial class DT_RefPOHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bUDATField;
        
        private string bLDATField;
        
        private string xBLNRField;
        
        private string bKTXTField;
        
        private string fRBNRField;
        
        private string xABLNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BUDAT {
            get {
                return this.bUDATField;
            }
            set {
                this.bUDATField = value;
                this.RaisePropertyChanged("BUDAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string BLDAT {
            get {
                return this.bLDATField;
            }
            set {
                this.bLDATField = value;
                this.RaisePropertyChanged("BLDAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string XBLNR {
            get {
                return this.xBLNRField;
            }
            set {
                this.xBLNRField = value;
                this.RaisePropertyChanged("XBLNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BKTXT {
            get {
                return this.bKTXTField;
            }
            set {
                this.bKTXTField = value;
                this.RaisePropertyChanged("BKTXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string FRBNR {
            get {
                return this.fRBNRField;
            }
            set {
                this.fRBNRField = value;
                this.RaisePropertyChanged("FRBNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string XABLN {
            get {
                return this.xABLNField;
            }
            set {
                this.xABLNField = value;
                this.RaisePropertyChanged("XABLN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:scg.co.th:CBMR:EPURCHASING:STOCK")]
    public partial class DT_RefPOReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_RefPOReturnReturn returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_RefPOReturnReturn Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("Return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:CBMR:EPURCHASING:STOCK")]
    public partial class DT_RefPOReturnReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        private string mBLNRField;
        
        private string mJAHRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MBLNR {
            get {
                return this.mBLNRField;
            }
            set {
                this.mBLNRField = value;
                this.RaisePropertyChanged("MBLNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MJAHR {
            get {
                return this.mJAHRField;
            }
            set {
                this.mJAHRField = value;
                this.RaisePropertyChanged("MJAHR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:CBMR:EPURCHASING:STOCK")]
    public partial class DT_RefPOItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bWARTField;
        
        private string mATNRField;
        
        private string wERKSField;
        
        private string lGORTField;
        
        private string mENGEField;
        
        private string mEINSField;
        
        private string gRUNDField;
        
        private string eBELNField;
        
        private string eBELPField;
        
        private string eLIKZField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BWART {
            get {
                return this.bWARTField;
            }
            set {
                this.bWARTField = value;
                this.RaisePropertyChanged("BWART");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
                this.RaisePropertyChanged("MATNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string LGORT {
            get {
                return this.lGORTField;
            }
            set {
                this.lGORTField = value;
                this.RaisePropertyChanged("LGORT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MENGE {
            get {
                return this.mENGEField;
            }
            set {
                this.mENGEField = value;
                this.RaisePropertyChanged("MENGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MEINS {
            get {
                return this.mEINSField;
            }
            set {
                this.mEINSField = value;
                this.RaisePropertyChanged("MEINS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string GRUND {
            get {
                return this.gRUNDField;
            }
            set {
                this.gRUNDField = value;
                this.RaisePropertyChanged("GRUND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
                this.RaisePropertyChanged("EBELN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string EBELP {
            get {
                return this.eBELPField;
            }
            set {
                this.eBELPField = value;
                this.RaisePropertyChanged("EBELP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ELIKZ {
            get {
                return this.eLIKZField;
            }
            set {
                this.eLIKZField = value;
                this.RaisePropertyChanged("ELIKZ");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_RefPORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:scg.co.th:CBMR:EPURCHASING:STOCK", Order=0)]
        public AddonProcurement.SI_RefPO_EPURServiceReference.DT_RefPO MT_RefPO;
        
        public SI_RefPORequest() {
        }
        
        public SI_RefPORequest(AddonProcurement.SI_RefPO_EPURServiceReference.DT_RefPO MT_RefPO) {
            this.MT_RefPO = MT_RefPO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_RefPOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:scg.co.th:CBMR:EPURCHASING:STOCK", Order=0)]
        public AddonProcurement.SI_RefPO_EPURServiceReference.DT_RefPOReturn MT_RefPOReturn;
        
        public SI_RefPOResponse() {
        }
        
        public SI_RefPOResponse(AddonProcurement.SI_RefPO_EPURServiceReference.DT_RefPOReturn MT_RefPOReturn) {
            this.MT_RefPOReturn = MT_RefPOReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_RefPOChannel : AddonProcurement.SI_RefPO_EPURServiceReference.SI_RefPO, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_RefPOClient : System.ServiceModel.ClientBase<AddonProcurement.SI_RefPO_EPURServiceReference.SI_RefPO>, AddonProcurement.SI_RefPO_EPURServiceReference.SI_RefPO {
        
        public SI_RefPOClient() {
        }
        
        public SI_RefPOClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_RefPOClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_RefPOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_RefPOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AddonProcurement.SI_RefPO_EPURServiceReference.SI_RefPOResponse AddonProcurement.SI_RefPO_EPURServiceReference.SI_RefPO.SI_RefPO(AddonProcurement.SI_RefPO_EPURServiceReference.SI_RefPORequest request) {
            return base.Channel.SI_RefPO(request);
        }
        
        public AddonProcurement.SI_RefPO_EPURServiceReference.DT_RefPOReturn SI_RefPO(AddonProcurement.SI_RefPO_EPURServiceReference.DT_RefPO MT_RefPO) {
            AddonProcurement.SI_RefPO_EPURServiceReference.SI_RefPORequest inValue = new AddonProcurement.SI_RefPO_EPURServiceReference.SI_RefPORequest();
            inValue.MT_RefPO = MT_RefPO;
            AddonProcurement.SI_RefPO_EPURServiceReference.SI_RefPOResponse retVal = ((AddonProcurement.SI_RefPO_EPURServiceReference.SI_RefPO)(this)).SI_RefPO(inValue);
            return retVal.MT_RefPOReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AddonProcurement.SI_RefPO_EPURServiceReference.SI_RefPOResponse> AddonProcurement.SI_RefPO_EPURServiceReference.SI_RefPO.SI_RefPOAsync(AddonProcurement.SI_RefPO_EPURServiceReference.SI_RefPORequest request) {
            return base.Channel.SI_RefPOAsync(request);
        }
        
        public System.Threading.Tasks.Task<AddonProcurement.SI_RefPO_EPURServiceReference.SI_RefPOResponse> SI_RefPOAsync(AddonProcurement.SI_RefPO_EPURServiceReference.DT_RefPO MT_RefPO) {
            AddonProcurement.SI_RefPO_EPURServiceReference.SI_RefPORequest inValue = new AddonProcurement.SI_RefPO_EPURServiceReference.SI_RefPORequest();
            inValue.MT_RefPO = MT_RefPO;
            return ((AddonProcurement.SI_RefPO_EPURServiceReference.SI_RefPO)(this)).SI_RefPOAsync(inValue);
        }
    }
}
