//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddonProcurement.VendorMasterServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:thailife.com:ACT:AP:API003", ConfigurationName="VendorMasterServiceReference.SI_TLI_BPMaster_SYNC_SND")]
    public interface SI_TLI_BPMaster_SYNC_SND {
        
        // CODEGEN: Generating message contract since the operation SI_TLI_BPMaster_SYNC_SND is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AddonProcurement.VendorMasterServiceReference.SI_TLI_BPMaster_SYNC_SNDResponse SI_TLI_BPMaster_SYNC_SND(AddonProcurement.VendorMasterServiceReference.SI_TLI_BPMaster_SYNC_SNDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<AddonProcurement.VendorMasterServiceReference.SI_TLI_BPMaster_SYNC_SNDResponse> SI_TLI_BPMaster_SYNC_SNDAsync(AddonProcurement.VendorMasterServiceReference.SI_TLI_BPMaster_SYNC_SNDRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:thailife.com:ACT:AP:API003")]
    public partial class DT_TLI_API003_SNDRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string activityField;
        
        private string partnerNumberField;
        
        private string bPGroupField;
        
        private string name1Field;
        
        private string name2Field;
        
        private string name3Field;
        
        private string name4Field;
        
        private string searchTerm1Field;
        
        private string searchTerm2Field;
        
        private string streetField;
        
        private string street2Field;
        
        private string street3Field;
        
        private string street4Field;
        
        private string dirtricField;
        
        private string postalCodeField;
        
        private string cityField;
        
        private string countryField;
        
        private string taxCategoryField;
        
        private string taxIDField;
        
        private string tradingPartnerField;
        
        private string idField;
        
        private string bankCountryField;
        
        private string bankKeyField;
        
        private string bankAccountNumberField;
        
        private string instructionKeyField;
        
        private string companyCodeField;
        
        private string reconciliationAcctField;
        
        private string sortKeyField;
        
        private string paymentTermField;
        
        private string paymentMethodField;
        
        private string wHTType1Field;
        
        private string subjectTax1Field;
        
        private string wHTCode1Field;
        
        private string typeOfRecipient1Field;
        
        private string wHTType2Field;
        
        private string subjectTax2Field;
        
        private string wHTCode2Field;
        
        private string typeOfRecipient2Field;
        
        private string wHTType3Field;
        
        private string subjectTax3Field;
        
        private string wHTCode3Field;
        
        private string typeOfRecipient3Field;
        
        private string wHTType4Field;
        
        private string subjectTax4Field;
        
        private string wHTCode4Field;
        
        private string typeOfRecipient4Field;
        
        private string branchField;
        
        private string branchDesField;
        
        private string postingBlockField;
        
        private string markForDeleteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Activity {
            get {
                return this.activityField;
            }
            set {
                this.activityField = value;
                this.RaisePropertyChanged("Activity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PartnerNumber {
            get {
                return this.partnerNumberField;
            }
            set {
                this.partnerNumberField = value;
                this.RaisePropertyChanged("PartnerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string BPGroup {
            get {
                return this.bPGroupField;
            }
            set {
                this.bPGroupField = value;
                this.RaisePropertyChanged("BPGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Name1 {
            get {
                return this.name1Field;
            }
            set {
                this.name1Field = value;
                this.RaisePropertyChanged("Name1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Name2 {
            get {
                return this.name2Field;
            }
            set {
                this.name2Field = value;
                this.RaisePropertyChanged("Name2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Name3 {
            get {
                return this.name3Field;
            }
            set {
                this.name3Field = value;
                this.RaisePropertyChanged("Name3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Name4 {
            get {
                return this.name4Field;
            }
            set {
                this.name4Field = value;
                this.RaisePropertyChanged("Name4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string SearchTerm1 {
            get {
                return this.searchTerm1Field;
            }
            set {
                this.searchTerm1Field = value;
                this.RaisePropertyChanged("SearchTerm1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SearchTerm2 {
            get {
                return this.searchTerm2Field;
            }
            set {
                this.searchTerm2Field = value;
                this.RaisePropertyChanged("SearchTerm2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Street2 {
            get {
                return this.street2Field;
            }
            set {
                this.street2Field = value;
                this.RaisePropertyChanged("Street2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Street3 {
            get {
                return this.street3Field;
            }
            set {
                this.street3Field = value;
                this.RaisePropertyChanged("Street3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Street4 {
            get {
                return this.street4Field;
            }
            set {
                this.street4Field = value;
                this.RaisePropertyChanged("Street4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Dirtric {
            get {
                return this.dirtricField;
            }
            set {
                this.dirtricField = value;
                this.RaisePropertyChanged("Dirtric");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string TaxCategory {
            get {
                return this.taxCategoryField;
            }
            set {
                this.taxCategoryField = value;
                this.RaisePropertyChanged("TaxCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string TaxID {
            get {
                return this.taxIDField;
            }
            set {
                this.taxIDField = value;
                this.RaisePropertyChanged("TaxID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string TradingPartner {
            get {
                return this.tradingPartnerField;
            }
            set {
                this.tradingPartnerField = value;
                this.RaisePropertyChanged("TradingPartner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string BankCountry {
            get {
                return this.bankCountryField;
            }
            set {
                this.bankCountryField = value;
                this.RaisePropertyChanged("BankCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string BankKey {
            get {
                return this.bankKeyField;
            }
            set {
                this.bankKeyField = value;
                this.RaisePropertyChanged("BankKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string BankAccountNumber {
            get {
                return this.bankAccountNumberField;
            }
            set {
                this.bankAccountNumberField = value;
                this.RaisePropertyChanged("BankAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string InstructionKey {
            get {
                return this.instructionKeyField;
            }
            set {
                this.instructionKeyField = value;
                this.RaisePropertyChanged("InstructionKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
                this.RaisePropertyChanged("CompanyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string ReconciliationAcct {
            get {
                return this.reconciliationAcctField;
            }
            set {
                this.reconciliationAcctField = value;
                this.RaisePropertyChanged("ReconciliationAcct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string SortKey {
            get {
                return this.sortKeyField;
            }
            set {
                this.sortKeyField = value;
                this.RaisePropertyChanged("SortKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string PaymentTerm {
            get {
                return this.paymentTermField;
            }
            set {
                this.paymentTermField = value;
                this.RaisePropertyChanged("PaymentTerm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string PaymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                this.paymentMethodField = value;
                this.RaisePropertyChanged("PaymentMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string WHTType1 {
            get {
                return this.wHTType1Field;
            }
            set {
                this.wHTType1Field = value;
                this.RaisePropertyChanged("WHTType1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string SubjectTax1 {
            get {
                return this.subjectTax1Field;
            }
            set {
                this.subjectTax1Field = value;
                this.RaisePropertyChanged("SubjectTax1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string WHTCode1 {
            get {
                return this.wHTCode1Field;
            }
            set {
                this.wHTCode1Field = value;
                this.RaisePropertyChanged("WHTCode1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string TypeOfRecipient1 {
            get {
                return this.typeOfRecipient1Field;
            }
            set {
                this.typeOfRecipient1Field = value;
                this.RaisePropertyChanged("TypeOfRecipient1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string WHTType2 {
            get {
                return this.wHTType2Field;
            }
            set {
                this.wHTType2Field = value;
                this.RaisePropertyChanged("WHTType2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string SubjectTax2 {
            get {
                return this.subjectTax2Field;
            }
            set {
                this.subjectTax2Field = value;
                this.RaisePropertyChanged("SubjectTax2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string WHTCode2 {
            get {
                return this.wHTCode2Field;
            }
            set {
                this.wHTCode2Field = value;
                this.RaisePropertyChanged("WHTCode2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string TypeOfRecipient2 {
            get {
                return this.typeOfRecipient2Field;
            }
            set {
                this.typeOfRecipient2Field = value;
                this.RaisePropertyChanged("TypeOfRecipient2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string WHTType3 {
            get {
                return this.wHTType3Field;
            }
            set {
                this.wHTType3Field = value;
                this.RaisePropertyChanged("WHTType3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string SubjectTax3 {
            get {
                return this.subjectTax3Field;
            }
            set {
                this.subjectTax3Field = value;
                this.RaisePropertyChanged("SubjectTax3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string WHTCode3 {
            get {
                return this.wHTCode3Field;
            }
            set {
                this.wHTCode3Field = value;
                this.RaisePropertyChanged("WHTCode3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string TypeOfRecipient3 {
            get {
                return this.typeOfRecipient3Field;
            }
            set {
                this.typeOfRecipient3Field = value;
                this.RaisePropertyChanged("TypeOfRecipient3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string WHTType4 {
            get {
                return this.wHTType4Field;
            }
            set {
                this.wHTType4Field = value;
                this.RaisePropertyChanged("WHTType4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string SubjectTax4 {
            get {
                return this.subjectTax4Field;
            }
            set {
                this.subjectTax4Field = value;
                this.RaisePropertyChanged("SubjectTax4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string WHTCode4 {
            get {
                return this.wHTCode4Field;
            }
            set {
                this.wHTCode4Field = value;
                this.RaisePropertyChanged("WHTCode4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string TypeOfRecipient4 {
            get {
                return this.typeOfRecipient4Field;
            }
            set {
                this.typeOfRecipient4Field = value;
                this.RaisePropertyChanged("TypeOfRecipient4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string Branch {
            get {
                return this.branchField;
            }
            set {
                this.branchField = value;
                this.RaisePropertyChanged("Branch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string BranchDes {
            get {
                return this.branchDesField;
            }
            set {
                this.branchDesField = value;
                this.RaisePropertyChanged("BranchDes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string PostingBlock {
            get {
                return this.postingBlockField;
            }
            set {
                this.postingBlockField = value;
                this.RaisePropertyChanged("PostingBlock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=49)]
        public string MarkForDelete {
            get {
                return this.markForDeleteField;
            }
            set {
                this.markForDeleteField = value;
                this.RaisePropertyChanged("MarkForDelete");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:thailife.com:ACT:AP:API003")]
    public partial class DT_RTN_API003_SNDItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        private string pARAMETERField;
        
        private string rOWField;
        
        private string fIELDField;
        
        private string sYSTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
                this.RaisePropertyChanged("NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_NO {
            get {
                return this.lOG_NOField;
            }
            set {
                this.lOG_NOField = value;
                this.RaisePropertyChanged("LOG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LOG_MSG_NO {
            get {
                return this.lOG_MSG_NOField;
            }
            set {
                this.lOG_MSG_NOField = value;
                this.RaisePropertyChanged("LOG_MSG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V1 {
            get {
                return this.mESSAGE_V1Field;
            }
            set {
                this.mESSAGE_V1Field = value;
                this.RaisePropertyChanged("MESSAGE_V1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V2 {
            get {
                return this.mESSAGE_V2Field;
            }
            set {
                this.mESSAGE_V2Field = value;
                this.RaisePropertyChanged("MESSAGE_V2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V3 {
            get {
                return this.mESSAGE_V3Field;
            }
            set {
                this.mESSAGE_V3Field = value;
                this.RaisePropertyChanged("MESSAGE_V3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MESSAGE_V4 {
            get {
                return this.mESSAGE_V4Field;
            }
            set {
                this.mESSAGE_V4Field = value;
                this.RaisePropertyChanged("MESSAGE_V4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PARAMETER {
            get {
                return this.pARAMETERField;
            }
            set {
                this.pARAMETERField = value;
                this.RaisePropertyChanged("PARAMETER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=11)]
        public string ROW {
            get {
                return this.rOWField;
            }
            set {
                this.rOWField = value;
                this.RaisePropertyChanged("ROW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FIELD {
            get {
                return this.fIELDField;
            }
            set {
                this.fIELDField = value;
                this.RaisePropertyChanged("FIELD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SYSTEM {
            get {
                return this.sYSTEMField;
            }
            set {
                this.sYSTEMField = value;
                this.RaisePropertyChanged("SYSTEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_TLI_BPMaster_SYNC_SNDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:thailife.com:ACT:AP:API003", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("row", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AddonProcurement.VendorMasterServiceReference.DT_TLI_API003_SNDRow[] MT_TLI_API003_SND;
        
        public SI_TLI_BPMaster_SYNC_SNDRequest() {
        }
        
        public SI_TLI_BPMaster_SYNC_SNDRequest(AddonProcurement.VendorMasterServiceReference.DT_TLI_API003_SNDRow[] MT_TLI_API003_SND) {
            this.MT_TLI_API003_SND = MT_TLI_API003_SND;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_TLI_BPMaster_SYNC_SNDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:thailife.com:ACT:AP:API003", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AddonProcurement.VendorMasterServiceReference.DT_RTN_API003_SNDItem[] MT_RTN_API003_SND;
        
        public SI_TLI_BPMaster_SYNC_SNDResponse() {
        }
        
        public SI_TLI_BPMaster_SYNC_SNDResponse(AddonProcurement.VendorMasterServiceReference.DT_RTN_API003_SNDItem[] MT_RTN_API003_SND) {
            this.MT_RTN_API003_SND = MT_RTN_API003_SND;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_TLI_BPMaster_SYNC_SNDChannel : AddonProcurement.VendorMasterServiceReference.SI_TLI_BPMaster_SYNC_SND, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_TLI_BPMaster_SYNC_SNDClient : System.ServiceModel.ClientBase<AddonProcurement.VendorMasterServiceReference.SI_TLI_BPMaster_SYNC_SND>, AddonProcurement.VendorMasterServiceReference.SI_TLI_BPMaster_SYNC_SND {
        
        public SI_TLI_BPMaster_SYNC_SNDClient() {
        }
        
        public SI_TLI_BPMaster_SYNC_SNDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_TLI_BPMaster_SYNC_SNDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_TLI_BPMaster_SYNC_SNDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_TLI_BPMaster_SYNC_SNDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AddonProcurement.VendorMasterServiceReference.SI_TLI_BPMaster_SYNC_SNDResponse AddonProcurement.VendorMasterServiceReference.SI_TLI_BPMaster_SYNC_SND.SI_TLI_BPMaster_SYNC_SND(AddonProcurement.VendorMasterServiceReference.SI_TLI_BPMaster_SYNC_SNDRequest request) {
            return base.Channel.SI_TLI_BPMaster_SYNC_SND(request);
        }
        
        public AddonProcurement.VendorMasterServiceReference.DT_RTN_API003_SNDItem[] SI_TLI_BPMaster_SYNC_SND(AddonProcurement.VendorMasterServiceReference.DT_TLI_API003_SNDRow[] MT_TLI_API003_SND) {
            AddonProcurement.VendorMasterServiceReference.SI_TLI_BPMaster_SYNC_SNDRequest inValue = new AddonProcurement.VendorMasterServiceReference.SI_TLI_BPMaster_SYNC_SNDRequest();
            inValue.MT_TLI_API003_SND = MT_TLI_API003_SND;
            AddonProcurement.VendorMasterServiceReference.SI_TLI_BPMaster_SYNC_SNDResponse retVal = ((AddonProcurement.VendorMasterServiceReference.SI_TLI_BPMaster_SYNC_SND)(this)).SI_TLI_BPMaster_SYNC_SND(inValue);
            return retVal.MT_RTN_API003_SND;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AddonProcurement.VendorMasterServiceReference.SI_TLI_BPMaster_SYNC_SNDResponse> AddonProcurement.VendorMasterServiceReference.SI_TLI_BPMaster_SYNC_SND.SI_TLI_BPMaster_SYNC_SNDAsync(AddonProcurement.VendorMasterServiceReference.SI_TLI_BPMaster_SYNC_SNDRequest request) {
            return base.Channel.SI_TLI_BPMaster_SYNC_SNDAsync(request);
        }
        
        public System.Threading.Tasks.Task<AddonProcurement.VendorMasterServiceReference.SI_TLI_BPMaster_SYNC_SNDResponse> SI_TLI_BPMaster_SYNC_SNDAsync(AddonProcurement.VendorMasterServiceReference.DT_TLI_API003_SNDRow[] MT_TLI_API003_SND) {
            AddonProcurement.VendorMasterServiceReference.SI_TLI_BPMaster_SYNC_SNDRequest inValue = new AddonProcurement.VendorMasterServiceReference.SI_TLI_BPMaster_SYNC_SNDRequest();
            inValue.MT_TLI_API003_SND = MT_TLI_API003_SND;
            return ((AddonProcurement.VendorMasterServiceReference.SI_TLI_BPMaster_SYNC_SND)(this)).SI_TLI_BPMaster_SYNC_SNDAsync(inValue);
        }
    }
}
