//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddonProcurement.SI_POCreateServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:scg.co.th:CBMR:EPURCHASING:PO", ConfigurationName="SI_POCreateServiceReference.SI_POCreate")]
    public interface SI_POCreate {
        
        // CODEGEN: Generating message contract since the operation SI_POCreate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AddonProcurement.SI_POCreateServiceReference.SI_POCreateResponse SI_POCreate(AddonProcurement.SI_POCreateServiceReference.SI_POCreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<AddonProcurement.SI_POCreateServiceReference.SI_POCreateResponse> SI_POCreateAsync(AddonProcurement.SI_POCreateServiceReference.SI_POCreateRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:scg.co.th:CBMR:EPURCHASING:PO")]
    public partial class DT_POCreate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_POCreateHeader headerField;
        
        private DT_POCreateItem[] itemField;
        
        private DT_POCreateAccountAssignment[] accountAssignmentField;
        
        private DT_POCreateConditionHeader[] conditionHeaderField;
        
        private DT_POCreateConditionItem[] conditionItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_POCreateHeader Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("Header");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_POCreateItem[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AccountAssignment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DT_POCreateAccountAssignment[] AccountAssignment {
            get {
                return this.accountAssignmentField;
            }
            set {
                this.accountAssignmentField = value;
                this.RaisePropertyChanged("AccountAssignment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionHeader", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public DT_POCreateConditionHeader[] ConditionHeader {
            get {
                return this.conditionHeaderField;
            }
            set {
                this.conditionHeaderField = value;
                this.RaisePropertyChanged("ConditionHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public DT_POCreateConditionItem[] ConditionItem {
            get {
                return this.conditionItemField;
            }
            set {
                this.conditionItemField = value;
                this.RaisePropertyChanged("ConditionItem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:CBMR:EPURCHASING:PO")]
    public partial class DT_POCreateHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pO_NOField;
        
        private string pO_TYPEField;
        
        private string pO_TYPE_DESCField;
        
        private string pO_CREATE_BYField;
        
        private string pO_VENDORField;
        
        private string pO_VENDOR_NAMEField;
        
        private string pO_VENDOR_EMAILField;
        
        private string pO_VENDOR_FAXField;
        
        private string pO_VENDOR_EXTENSIONField;
        
        private string pO_VENDOR_ADDRESSField;
        
        private string pO_VENDOR_CITYField;
        
        private string pO_VENDOR_COUNTRYKEYField;
        
        private string pO_DOC_DATEField;
        
        private string pO_PAYMENT_TERMField;
        
        private string pO_PAYMENT_TERM_DESCField;
        
        private string pO_INCOTERMField;
        
        private string pO_INCOTERM_DESCField;
        
        private string pO_CURRField;
        
        private string pO_EXCHField;
        
        private string pO_HEADER_NOTEField;
        
        private string pO_PUR_ORGField;
        
        private string pO_PUR_GRPField;
        
        private string pO_COM_CODEField;
        
        private string pO_COM_NAMEField;
        
        private string pO_REL1Field;
        
        private string pO_REL_TXT1Field;
        
        private string pO_CURR_LEVELField;
        
        private string pO_TOTALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PO_NO {
            get {
                return this.pO_NOField;
            }
            set {
                this.pO_NOField = value;
                this.RaisePropertyChanged("PO_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PO_TYPE {
            get {
                return this.pO_TYPEField;
            }
            set {
                this.pO_TYPEField = value;
                this.RaisePropertyChanged("PO_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PO_TYPE_DESC {
            get {
                return this.pO_TYPE_DESCField;
            }
            set {
                this.pO_TYPE_DESCField = value;
                this.RaisePropertyChanged("PO_TYPE_DESC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string PO_CREATE_BY {
            get {
                return this.pO_CREATE_BYField;
            }
            set {
                this.pO_CREATE_BYField = value;
                this.RaisePropertyChanged("PO_CREATE_BY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PO_VENDOR {
            get {
                return this.pO_VENDORField;
            }
            set {
                this.pO_VENDORField = value;
                this.RaisePropertyChanged("PO_VENDOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string PO_VENDOR_NAME {
            get {
                return this.pO_VENDOR_NAMEField;
            }
            set {
                this.pO_VENDOR_NAMEField = value;
                this.RaisePropertyChanged("PO_VENDOR_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string PO_VENDOR_EMAIL {
            get {
                return this.pO_VENDOR_EMAILField;
            }
            set {
                this.pO_VENDOR_EMAILField = value;
                this.RaisePropertyChanged("PO_VENDOR_EMAIL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string PO_VENDOR_FAX {
            get {
                return this.pO_VENDOR_FAXField;
            }
            set {
                this.pO_VENDOR_FAXField = value;
                this.RaisePropertyChanged("PO_VENDOR_FAX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string PO_VENDOR_EXTENSION {
            get {
                return this.pO_VENDOR_EXTENSIONField;
            }
            set {
                this.pO_VENDOR_EXTENSIONField = value;
                this.RaisePropertyChanged("PO_VENDOR_EXTENSION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string PO_VENDOR_ADDRESS {
            get {
                return this.pO_VENDOR_ADDRESSField;
            }
            set {
                this.pO_VENDOR_ADDRESSField = value;
                this.RaisePropertyChanged("PO_VENDOR_ADDRESS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PO_VENDOR_CITY {
            get {
                return this.pO_VENDOR_CITYField;
            }
            set {
                this.pO_VENDOR_CITYField = value;
                this.RaisePropertyChanged("PO_VENDOR_CITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string PO_VENDOR_COUNTRYKEY {
            get {
                return this.pO_VENDOR_COUNTRYKEYField;
            }
            set {
                this.pO_VENDOR_COUNTRYKEYField = value;
                this.RaisePropertyChanged("PO_VENDOR_COUNTRYKEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string PO_DOC_DATE {
            get {
                return this.pO_DOC_DATEField;
            }
            set {
                this.pO_DOC_DATEField = value;
                this.RaisePropertyChanged("PO_DOC_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string PO_PAYMENT_TERM {
            get {
                return this.pO_PAYMENT_TERMField;
            }
            set {
                this.pO_PAYMENT_TERMField = value;
                this.RaisePropertyChanged("PO_PAYMENT_TERM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string PO_PAYMENT_TERM_DESC {
            get {
                return this.pO_PAYMENT_TERM_DESCField;
            }
            set {
                this.pO_PAYMENT_TERM_DESCField = value;
                this.RaisePropertyChanged("PO_PAYMENT_TERM_DESC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string PO_INCOTERM {
            get {
                return this.pO_INCOTERMField;
            }
            set {
                this.pO_INCOTERMField = value;
                this.RaisePropertyChanged("PO_INCOTERM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string PO_INCOTERM_DESC {
            get {
                return this.pO_INCOTERM_DESCField;
            }
            set {
                this.pO_INCOTERM_DESCField = value;
                this.RaisePropertyChanged("PO_INCOTERM_DESC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string PO_CURR {
            get {
                return this.pO_CURRField;
            }
            set {
                this.pO_CURRField = value;
                this.RaisePropertyChanged("PO_CURR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string PO_EXCH {
            get {
                return this.pO_EXCHField;
            }
            set {
                this.pO_EXCHField = value;
                this.RaisePropertyChanged("PO_EXCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string PO_HEADER_NOTE {
            get {
                return this.pO_HEADER_NOTEField;
            }
            set {
                this.pO_HEADER_NOTEField = value;
                this.RaisePropertyChanged("PO_HEADER_NOTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string PO_PUR_ORG {
            get {
                return this.pO_PUR_ORGField;
            }
            set {
                this.pO_PUR_ORGField = value;
                this.RaisePropertyChanged("PO_PUR_ORG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string PO_PUR_GRP {
            get {
                return this.pO_PUR_GRPField;
            }
            set {
                this.pO_PUR_GRPField = value;
                this.RaisePropertyChanged("PO_PUR_GRP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string PO_COM_CODE {
            get {
                return this.pO_COM_CODEField;
            }
            set {
                this.pO_COM_CODEField = value;
                this.RaisePropertyChanged("PO_COM_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string PO_COM_NAME {
            get {
                return this.pO_COM_NAMEField;
            }
            set {
                this.pO_COM_NAMEField = value;
                this.RaisePropertyChanged("PO_COM_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string PO_REL1 {
            get {
                return this.pO_REL1Field;
            }
            set {
                this.pO_REL1Field = value;
                this.RaisePropertyChanged("PO_REL1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string PO_REL_TXT1 {
            get {
                return this.pO_REL_TXT1Field;
            }
            set {
                this.pO_REL_TXT1Field = value;
                this.RaisePropertyChanged("PO_REL_TXT1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string PO_CURR_LEVEL {
            get {
                return this.pO_CURR_LEVELField;
            }
            set {
                this.pO_CURR_LEVELField = value;
                this.RaisePropertyChanged("PO_CURR_LEVEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string PO_TOTAL {
            get {
                return this.pO_TOTALField;
            }
            set {
                this.pO_TOTALField = value;
                this.RaisePropertyChanged("PO_TOTAL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:scg.co.th:CBMR:EPURCHASING:PO")]
    public partial class DT_POReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_POReturnHeader[] headerField;
        
        private DT_POReturnItem[] itemField;
        
        private DT_POReturnConditionHeader[] conditionHeaderField;
        
        private DT_POReturnConditionItem[] conditionItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Header", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_POReturnHeader[] Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("Header");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_POReturnItem[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionHeader", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DT_POReturnConditionHeader[] ConditionHeader {
            get {
                return this.conditionHeaderField;
            }
            set {
                this.conditionHeaderField = value;
                this.RaisePropertyChanged("ConditionHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public DT_POReturnConditionItem[] ConditionItem {
            get {
                return this.conditionItemField;
            }
            set {
                this.conditionItemField = value;
                this.RaisePropertyChanged("ConditionItem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:CBMR:EPURCHASING:PO")]
    public partial class DT_POReturnHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        private string pO_NOField;
        
        private string pO_CURRField;
        
        private string pO_EXCHField;
        
        private string pO_TOTALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PO_NO {
            get {
                return this.pO_NOField;
            }
            set {
                this.pO_NOField = value;
                this.RaisePropertyChanged("PO_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string PO_CURR {
            get {
                return this.pO_CURRField;
            }
            set {
                this.pO_CURRField = value;
                this.RaisePropertyChanged("PO_CURR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PO_EXCH {
            get {
                return this.pO_EXCHField;
            }
            set {
                this.pO_EXCHField = value;
                this.RaisePropertyChanged("PO_EXCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string PO_TOTAL {
            get {
                return this.pO_TOTALField;
            }
            set {
                this.pO_TOTALField = value;
                this.RaisePropertyChanged("PO_TOTAL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:CBMR:EPURCHASING:PO")]
    public partial class DT_POReturnItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pO_ITEM_NOField;
        
        private string pO_MAT_NOField;
        
        private string pO_MAT_SHORT_TXTField;
        
        private string pO_QTYField;
        
        private string pO_ORDER_UNITField;
        
        private string pO_NET_PRICEField;
        
        private string pO_CONV_OUNField;
        
        private string pO_CONV_OPUField;
        
        private string pO_PRICE_PER_UNITField;
        
        private string pO_NET_VELUEField;
        
        private string pO_PLANTField;
        
        private string pO_PLANT_DESCField;
        
        private string pO_VAT_VALUEField;
        
        private string pO_TAXCODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PO_ITEM_NO {
            get {
                return this.pO_ITEM_NOField;
            }
            set {
                this.pO_ITEM_NOField = value;
                this.RaisePropertyChanged("PO_ITEM_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PO_MAT_NO {
            get {
                return this.pO_MAT_NOField;
            }
            set {
                this.pO_MAT_NOField = value;
                this.RaisePropertyChanged("PO_MAT_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PO_MAT_SHORT_TXT {
            get {
                return this.pO_MAT_SHORT_TXTField;
            }
            set {
                this.pO_MAT_SHORT_TXTField = value;
                this.RaisePropertyChanged("PO_MAT_SHORT_TXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string PO_QTY {
            get {
                return this.pO_QTYField;
            }
            set {
                this.pO_QTYField = value;
                this.RaisePropertyChanged("PO_QTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PO_ORDER_UNIT {
            get {
                return this.pO_ORDER_UNITField;
            }
            set {
                this.pO_ORDER_UNITField = value;
                this.RaisePropertyChanged("PO_ORDER_UNIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string PO_NET_PRICE {
            get {
                return this.pO_NET_PRICEField;
            }
            set {
                this.pO_NET_PRICEField = value;
                this.RaisePropertyChanged("PO_NET_PRICE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string PO_CONV_OUN {
            get {
                return this.pO_CONV_OUNField;
            }
            set {
                this.pO_CONV_OUNField = value;
                this.RaisePropertyChanged("PO_CONV_OUN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string PO_CONV_OPU {
            get {
                return this.pO_CONV_OPUField;
            }
            set {
                this.pO_CONV_OPUField = value;
                this.RaisePropertyChanged("PO_CONV_OPU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string PO_PRICE_PER_UNIT {
            get {
                return this.pO_PRICE_PER_UNITField;
            }
            set {
                this.pO_PRICE_PER_UNITField = value;
                this.RaisePropertyChanged("PO_PRICE_PER_UNIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string PO_NET_VELUE {
            get {
                return this.pO_NET_VELUEField;
            }
            set {
                this.pO_NET_VELUEField = value;
                this.RaisePropertyChanged("PO_NET_VELUE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PO_PLANT {
            get {
                return this.pO_PLANTField;
            }
            set {
                this.pO_PLANTField = value;
                this.RaisePropertyChanged("PO_PLANT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string PO_PLANT_DESC {
            get {
                return this.pO_PLANT_DESCField;
            }
            set {
                this.pO_PLANT_DESCField = value;
                this.RaisePropertyChanged("PO_PLANT_DESC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string PO_VAT_VALUE {
            get {
                return this.pO_VAT_VALUEField;
            }
            set {
                this.pO_VAT_VALUEField = value;
                this.RaisePropertyChanged("PO_VAT_VALUE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string PO_TAXCODE {
            get {
                return this.pO_TAXCODEField;
            }
            set {
                this.pO_TAXCODEField = value;
                this.RaisePropertyChanged("PO_TAXCODE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:CBMR:EPURCHASING:PO")]
    public partial class DT_POReturnConditionHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pO_COND_TPField;
        
        private string pO_COND_RTField;
        
        private string pO_COND_CURRField;
        
        private string pO_COND_PRC_UNITField;
        
        private string pO_COND_UNITField;
        
        private string pO_COND_VENField;
        
        private string pO_COND_VALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PO_COND_TP {
            get {
                return this.pO_COND_TPField;
            }
            set {
                this.pO_COND_TPField = value;
                this.RaisePropertyChanged("PO_COND_TP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PO_COND_RT {
            get {
                return this.pO_COND_RTField;
            }
            set {
                this.pO_COND_RTField = value;
                this.RaisePropertyChanged("PO_COND_RT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PO_COND_CURR {
            get {
                return this.pO_COND_CURRField;
            }
            set {
                this.pO_COND_CURRField = value;
                this.RaisePropertyChanged("PO_COND_CURR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string PO_COND_PRC_UNIT {
            get {
                return this.pO_COND_PRC_UNITField;
            }
            set {
                this.pO_COND_PRC_UNITField = value;
                this.RaisePropertyChanged("PO_COND_PRC_UNIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PO_COND_UNIT {
            get {
                return this.pO_COND_UNITField;
            }
            set {
                this.pO_COND_UNITField = value;
                this.RaisePropertyChanged("PO_COND_UNIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string PO_COND_VEN {
            get {
                return this.pO_COND_VENField;
            }
            set {
                this.pO_COND_VENField = value;
                this.RaisePropertyChanged("PO_COND_VEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string PO_COND_VAL {
            get {
                return this.pO_COND_VALField;
            }
            set {
                this.pO_COND_VALField = value;
                this.RaisePropertyChanged("PO_COND_VAL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:CBMR:EPURCHASING:PO")]
    public partial class DT_POReturnConditionItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pO_COND_ITEMField;
        
        private string pO_COND_TPField;
        
        private string pO_COND_RTField;
        
        private string pO_COND_CURRField;
        
        private string pO_COND_PRC_UNITField;
        
        private string pO_COND_UNITField;
        
        private string pO_COND_VENField;
        
        private string pO_COND_VALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PO_COND_ITEM {
            get {
                return this.pO_COND_ITEMField;
            }
            set {
                this.pO_COND_ITEMField = value;
                this.RaisePropertyChanged("PO_COND_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PO_COND_TP {
            get {
                return this.pO_COND_TPField;
            }
            set {
                this.pO_COND_TPField = value;
                this.RaisePropertyChanged("PO_COND_TP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PO_COND_RT {
            get {
                return this.pO_COND_RTField;
            }
            set {
                this.pO_COND_RTField = value;
                this.RaisePropertyChanged("PO_COND_RT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string PO_COND_CURR {
            get {
                return this.pO_COND_CURRField;
            }
            set {
                this.pO_COND_CURRField = value;
                this.RaisePropertyChanged("PO_COND_CURR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PO_COND_PRC_UNIT {
            get {
                return this.pO_COND_PRC_UNITField;
            }
            set {
                this.pO_COND_PRC_UNITField = value;
                this.RaisePropertyChanged("PO_COND_PRC_UNIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string PO_COND_UNIT {
            get {
                return this.pO_COND_UNITField;
            }
            set {
                this.pO_COND_UNITField = value;
                this.RaisePropertyChanged("PO_COND_UNIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string PO_COND_VEN {
            get {
                return this.pO_COND_VENField;
            }
            set {
                this.pO_COND_VENField = value;
                this.RaisePropertyChanged("PO_COND_VEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string PO_COND_VAL {
            get {
                return this.pO_COND_VALField;
            }
            set {
                this.pO_COND_VALField = value;
                this.RaisePropertyChanged("PO_COND_VAL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:CBMR:EPURCHASING:PO")]
    public partial class DT_POCreateItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pO_ITEM_NOField;
        
        private string pO_DEL_INDField;
        
        private string pO_ACC_CATField;
        
        private string pO_MAT_NOField;
        
        private string pO_MAT_SHORT_TXTField;
        
        private string pO_QTYField;
        
        private string pO_ORDER_UNITField;
        
        private string pO_DEL_DATEField;
        
        private string pO_NET_PRICEField;
        
        private string pO_CONV_OUNField;
        
        private string pO_CONV_OPUField;
        
        private string pO_NET_VELUEField;
        
        private string pO_PLANTField;
        
        private string pO_PLANT_DESCField;
        
        private string pR_NOField;
        
        private string pR_ITEM_NOField;
        
        private string pO_TAXCODEField;
        
        private string pO_DELIVERY_COMPField;
        
        private string pO_FINAL_INVField;
        
        private string pO_OVERDEL_TOLField;
        
        private string pO_UNDERDEL_TOLField;
        
        private string pO_VENDOR_MAT_NOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PO_ITEM_NO {
            get {
                return this.pO_ITEM_NOField;
            }
            set {
                this.pO_ITEM_NOField = value;
                this.RaisePropertyChanged("PO_ITEM_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PO_DEL_IND {
            get {
                return this.pO_DEL_INDField;
            }
            set {
                this.pO_DEL_INDField = value;
                this.RaisePropertyChanged("PO_DEL_IND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PO_ACC_CAT {
            get {
                return this.pO_ACC_CATField;
            }
            set {
                this.pO_ACC_CATField = value;
                this.RaisePropertyChanged("PO_ACC_CAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string PO_MAT_NO {
            get {
                return this.pO_MAT_NOField;
            }
            set {
                this.pO_MAT_NOField = value;
                this.RaisePropertyChanged("PO_MAT_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PO_MAT_SHORT_TXT {
            get {
                return this.pO_MAT_SHORT_TXTField;
            }
            set {
                this.pO_MAT_SHORT_TXTField = value;
                this.RaisePropertyChanged("PO_MAT_SHORT_TXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string PO_QTY {
            get {
                return this.pO_QTYField;
            }
            set {
                this.pO_QTYField = value;
                this.RaisePropertyChanged("PO_QTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string PO_ORDER_UNIT {
            get {
                return this.pO_ORDER_UNITField;
            }
            set {
                this.pO_ORDER_UNITField = value;
                this.RaisePropertyChanged("PO_ORDER_UNIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string PO_DEL_DATE {
            get {
                return this.pO_DEL_DATEField;
            }
            set {
                this.pO_DEL_DATEField = value;
                this.RaisePropertyChanged("PO_DEL_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string PO_NET_PRICE {
            get {
                return this.pO_NET_PRICEField;
            }
            set {
                this.pO_NET_PRICEField = value;
                this.RaisePropertyChanged("PO_NET_PRICE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string PO_CONV_OUN {
            get {
                return this.pO_CONV_OUNField;
            }
            set {
                this.pO_CONV_OUNField = value;
                this.RaisePropertyChanged("PO_CONV_OUN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PO_CONV_OPU {
            get {
                return this.pO_CONV_OPUField;
            }
            set {
                this.pO_CONV_OPUField = value;
                this.RaisePropertyChanged("PO_CONV_OPU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string PO_NET_VELUE {
            get {
                return this.pO_NET_VELUEField;
            }
            set {
                this.pO_NET_VELUEField = value;
                this.RaisePropertyChanged("PO_NET_VELUE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string PO_PLANT {
            get {
                return this.pO_PLANTField;
            }
            set {
                this.pO_PLANTField = value;
                this.RaisePropertyChanged("PO_PLANT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string PO_PLANT_DESC {
            get {
                return this.pO_PLANT_DESCField;
            }
            set {
                this.pO_PLANT_DESCField = value;
                this.RaisePropertyChanged("PO_PLANT_DESC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string PR_NO {
            get {
                return this.pR_NOField;
            }
            set {
                this.pR_NOField = value;
                this.RaisePropertyChanged("PR_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string PR_ITEM_NO {
            get {
                return this.pR_ITEM_NOField;
            }
            set {
                this.pR_ITEM_NOField = value;
                this.RaisePropertyChanged("PR_ITEM_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string PO_TAXCODE {
            get {
                return this.pO_TAXCODEField;
            }
            set {
                this.pO_TAXCODEField = value;
                this.RaisePropertyChanged("PO_TAXCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string PO_DELIVERY_COMP {
            get {
                return this.pO_DELIVERY_COMPField;
            }
            set {
                this.pO_DELIVERY_COMPField = value;
                this.RaisePropertyChanged("PO_DELIVERY_COMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string PO_FINAL_INV {
            get {
                return this.pO_FINAL_INVField;
            }
            set {
                this.pO_FINAL_INVField = value;
                this.RaisePropertyChanged("PO_FINAL_INV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string PO_OVERDEL_TOL {
            get {
                return this.pO_OVERDEL_TOLField;
            }
            set {
                this.pO_OVERDEL_TOLField = value;
                this.RaisePropertyChanged("PO_OVERDEL_TOL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string PO_UNDERDEL_TOL {
            get {
                return this.pO_UNDERDEL_TOLField;
            }
            set {
                this.pO_UNDERDEL_TOLField = value;
                this.RaisePropertyChanged("PO_UNDERDEL_TOL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string PO_VENDOR_MAT_NO {
            get {
                return this.pO_VENDOR_MAT_NOField;
            }
            set {
                this.pO_VENDOR_MAT_NOField = value;
                this.RaisePropertyChanged("PO_VENDOR_MAT_NO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:CBMR:EPURCHASING:PO")]
    public partial class DT_POCreateAccountAssignment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pO_NOField;
        
        private string pO_ITEM_NOField;
        
        private string pO_GL_ACC_NOField;
        
        private string pO_BA_NOField;
        
        private string pO_COST_CTR_NOField;
        
        private string pO_ORDER_NOField;
        
        private string pO_ASSET_NOField;
        
        private string pO_ASSETSUB_NOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PO_NO {
            get {
                return this.pO_NOField;
            }
            set {
                this.pO_NOField = value;
                this.RaisePropertyChanged("PO_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PO_ITEM_NO {
            get {
                return this.pO_ITEM_NOField;
            }
            set {
                this.pO_ITEM_NOField = value;
                this.RaisePropertyChanged("PO_ITEM_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PO_GL_ACC_NO {
            get {
                return this.pO_GL_ACC_NOField;
            }
            set {
                this.pO_GL_ACC_NOField = value;
                this.RaisePropertyChanged("PO_GL_ACC_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string PO_BA_NO {
            get {
                return this.pO_BA_NOField;
            }
            set {
                this.pO_BA_NOField = value;
                this.RaisePropertyChanged("PO_BA_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PO_COST_CTR_NO {
            get {
                return this.pO_COST_CTR_NOField;
            }
            set {
                this.pO_COST_CTR_NOField = value;
                this.RaisePropertyChanged("PO_COST_CTR_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string PO_ORDER_NO {
            get {
                return this.pO_ORDER_NOField;
            }
            set {
                this.pO_ORDER_NOField = value;
                this.RaisePropertyChanged("PO_ORDER_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string PO_ASSET_NO {
            get {
                return this.pO_ASSET_NOField;
            }
            set {
                this.pO_ASSET_NOField = value;
                this.RaisePropertyChanged("PO_ASSET_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string PO_ASSETSUB_NO {
            get {
                return this.pO_ASSETSUB_NOField;
            }
            set {
                this.pO_ASSETSUB_NOField = value;
                this.RaisePropertyChanged("PO_ASSETSUB_NO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:CBMR:EPURCHASING:PO")]
    public partial class DT_POCreateConditionHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pO_COND_TPField;
        
        private string pO_COND_RTField;
        
        private string pO_COND_CURRField;
        
        private string pO_COND_VENField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PO_COND_TP {
            get {
                return this.pO_COND_TPField;
            }
            set {
                this.pO_COND_TPField = value;
                this.RaisePropertyChanged("PO_COND_TP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PO_COND_RT {
            get {
                return this.pO_COND_RTField;
            }
            set {
                this.pO_COND_RTField = value;
                this.RaisePropertyChanged("PO_COND_RT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PO_COND_CURR {
            get {
                return this.pO_COND_CURRField;
            }
            set {
                this.pO_COND_CURRField = value;
                this.RaisePropertyChanged("PO_COND_CURR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string PO_COND_VEN {
            get {
                return this.pO_COND_VENField;
            }
            set {
                this.pO_COND_VENField = value;
                this.RaisePropertyChanged("PO_COND_VEN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:CBMR:EPURCHASING:PO")]
    public partial class DT_POCreateConditionItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pO_COND_ITEMField;
        
        private string pO_COND_TPField;
        
        private string pO_COND_RTField;
        
        private string pO_COND_CURRField;
        
        private string pO_COND_PRC_UNITField;
        
        private string pO_COND_UNITField;
        
        private string pO_COND_VENField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PO_COND_ITEM {
            get {
                return this.pO_COND_ITEMField;
            }
            set {
                this.pO_COND_ITEMField = value;
                this.RaisePropertyChanged("PO_COND_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PO_COND_TP {
            get {
                return this.pO_COND_TPField;
            }
            set {
                this.pO_COND_TPField = value;
                this.RaisePropertyChanged("PO_COND_TP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PO_COND_RT {
            get {
                return this.pO_COND_RTField;
            }
            set {
                this.pO_COND_RTField = value;
                this.RaisePropertyChanged("PO_COND_RT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string PO_COND_CURR {
            get {
                return this.pO_COND_CURRField;
            }
            set {
                this.pO_COND_CURRField = value;
                this.RaisePropertyChanged("PO_COND_CURR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PO_COND_PRC_UNIT {
            get {
                return this.pO_COND_PRC_UNITField;
            }
            set {
                this.pO_COND_PRC_UNITField = value;
                this.RaisePropertyChanged("PO_COND_PRC_UNIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string PO_COND_UNIT {
            get {
                return this.pO_COND_UNITField;
            }
            set {
                this.pO_COND_UNITField = value;
                this.RaisePropertyChanged("PO_COND_UNIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string PO_COND_VEN {
            get {
                return this.pO_COND_VENField;
            }
            set {
                this.pO_COND_VENField = value;
                this.RaisePropertyChanged("PO_COND_VEN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_POCreateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:scg.co.th:CBMR:EPURCHASING:PO", Order=0)]
        public AddonProcurement.SI_POCreateServiceReference.DT_POCreate MT_POCreate;
        
        public SI_POCreateRequest() {
        }
        
        public SI_POCreateRequest(AddonProcurement.SI_POCreateServiceReference.DT_POCreate MT_POCreate) {
            this.MT_POCreate = MT_POCreate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_POCreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:scg.co.th:CBMR:EPURCHASING:PO", Order=0)]
        public AddonProcurement.SI_POCreateServiceReference.DT_POReturn MT_POReturn;
        
        public SI_POCreateResponse() {
        }
        
        public SI_POCreateResponse(AddonProcurement.SI_POCreateServiceReference.DT_POReturn MT_POReturn) {
            this.MT_POReturn = MT_POReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_POCreateChannel : AddonProcurement.SI_POCreateServiceReference.SI_POCreate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_POCreateClient : System.ServiceModel.ClientBase<AddonProcurement.SI_POCreateServiceReference.SI_POCreate>, AddonProcurement.SI_POCreateServiceReference.SI_POCreate {
        
        public SI_POCreateClient() {
        }
        
        public SI_POCreateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_POCreateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_POCreateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_POCreateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AddonProcurement.SI_POCreateServiceReference.SI_POCreateResponse AddonProcurement.SI_POCreateServiceReference.SI_POCreate.SI_POCreate(AddonProcurement.SI_POCreateServiceReference.SI_POCreateRequest request) {
            return base.Channel.SI_POCreate(request);
        }
        
        public AddonProcurement.SI_POCreateServiceReference.DT_POReturn SI_POCreate(AddonProcurement.SI_POCreateServiceReference.DT_POCreate MT_POCreate) {
            AddonProcurement.SI_POCreateServiceReference.SI_POCreateRequest inValue = new AddonProcurement.SI_POCreateServiceReference.SI_POCreateRequest();
            inValue.MT_POCreate = MT_POCreate;
            AddonProcurement.SI_POCreateServiceReference.SI_POCreateResponse retVal = ((AddonProcurement.SI_POCreateServiceReference.SI_POCreate)(this)).SI_POCreate(inValue);
            return retVal.MT_POReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AddonProcurement.SI_POCreateServiceReference.SI_POCreateResponse> AddonProcurement.SI_POCreateServiceReference.SI_POCreate.SI_POCreateAsync(AddonProcurement.SI_POCreateServiceReference.SI_POCreateRequest request) {
            return base.Channel.SI_POCreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<AddonProcurement.SI_POCreateServiceReference.SI_POCreateResponse> SI_POCreateAsync(AddonProcurement.SI_POCreateServiceReference.DT_POCreate MT_POCreate) {
            AddonProcurement.SI_POCreateServiceReference.SI_POCreateRequest inValue = new AddonProcurement.SI_POCreateServiceReference.SI_POCreateRequest();
            inValue.MT_POCreate = MT_POCreate;
            return ((AddonProcurement.SI_POCreateServiceReference.SI_POCreate)(this)).SI_POCreateAsync(inValue);
        }
    }
}
