//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddonProcurement.GRServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:thailife.com:ACT:AA:AAI001", ConfigurationName="GRServiceReference.SI_TLI_PurchaseOnline_SYNC_SND")]
    public interface SI_TLI_PurchaseOnline_SYNC_SND {
        
        // CODEGEN: Generating message contract since the operation SI_TLI_PurchaseOnline_SYNC_SND is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AddonProcurement.GRServiceReference.SI_TLI_PurchaseOnline_SYNC_SNDResponse SI_TLI_PurchaseOnline_SYNC_SND(AddonProcurement.GRServiceReference.SI_TLI_PurchaseOnline_SYNC_SNDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<AddonProcurement.GRServiceReference.SI_TLI_PurchaseOnline_SYNC_SNDResponse> SI_TLI_PurchaseOnline_SYNC_SNDAsync(AddonProcurement.GRServiceReference.SI_TLI_PurchaseOnline_SYNC_SNDRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:thailife.com:ACT:AA:AAI001")]
    public partial class DT_TLI_AAI001_SNDRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dCGRPField;
        
        private string lDGRPField;
        
        private string bUKRSField;
        
        private string bLARTField;
        
        private string bLDATField;
        
        private string xBLNRField;
        
        private string bUDATField;
        
        private string wAERSField;
        
        private string kURSFField;
        
        private string bKTXTField;
        
        private string xREF1_HDField;
        
        private string sTGRDField;
        
        private string sTODTField;
        
        private string nEWBSField;
        
        private string nEWUMField;
        
        private string lGACCField;
        
        private string aCCODField;
        
        private string nEWKOField;
        
        private string aNBWAField;
        
        private string wRBTRField;
        
        private string dMBTRField;
        
        private string sKFBTField;
        
        private string wSKTOField;
        
        private string mWSTSField;
        
        private string wMWSTField;
        
        private string mWSKZField;
        
        private string zFBDTField;
        
        private string zTERMField;
        
        private string zUONRField;
        
        private string sGTXTField;
        
        private string bUPLAField;
        
        private string xREF1Field;
        
        private string xREF2Field;
        
        private string xREF3Field;
        
        private string j_1TPBUPLField;
        
        private string vBUNDField;
        
        private string nAME1Field;
        
        private string nAME2Field;
        
        private string nAME3Field;
        
        private string nAME4Field;
        
        private string sTRASField;
        
        private string oRT01Field;
        
        private string pSTLZField;
        
        private string rEGIOField;
        
        private string lAND1Field;
        
        private string sTCD3Field;
        
        private string bANKLField;
        
        private string bANKNField;
        
        private string wITHT1Field;
        
        private string wT_WITHCD1Field;
        
        private string wT_QSSHH1Field;
        
        private string wT_QBSHH1Field;
        
        private string wITHT2Field;
        
        private string wT_WITHCD2Field;
        
        private string wT_QSSHH2Field;
        
        private string wT_QBSHH2Field;
        
        private string wITHT3Field;
        
        private string wT_WITHCD3Field;
        
        private string wT_QSSHH3Field;
        
        private string wT_QBSHH3Field;
        
        private string gSBERField;
        
        private string zZ01Field;
        
        private string zZ02Field;
        
        private string pRCTRField;
        
        private string zZ03Field;
        
        private string kOSTLField;
        
        private string zZ04Field;
        
        private string zZ05Field;
        
        private string zZ06Field;
        
        private string zZ07Field;
        
        private string aUFNRField;
        
        private string zZKOSTLField;
        
        private string qUNTYField;
        
        private string aNLKLField;
        
        private string nASSETSField;
        
        private string dES01Field;
        
        private string dES02Field;
        
        private string iNVNRField;
        
        private string mENGEField;
        
        private string mEINSField;
        
        private string iNKENField;
        
        private string kOSTLMField;
        
        private string kOSTLVField;
        
        private string cAUFNField;
        
        private string sEGMENTField;
        
        private string oRD41Field;
        
        private string gDLGRPField;
        
        private string tYPBZField;
        
        private string pUBTRField;
        
        private string tPBTRField;
        
        private string bELNRField;
        
        private string gJAHRField;
        
        private string tYPEField;
        
        private string cODEField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DCGRP {
            get {
                return this.dCGRPField;
            }
            set {
                this.dCGRPField = value;
                this.RaisePropertyChanged("DCGRP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string LDGRP {
            get {
                return this.lDGRPField;
            }
            set {
                this.lDGRPField = value;
                this.RaisePropertyChanged("LDGRP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
                this.RaisePropertyChanged("BUKRS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BLART {
            get {
                return this.bLARTField;
            }
            set {
                this.bLARTField = value;
                this.RaisePropertyChanged("BLART");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string BLDAT {
            get {
                return this.bLDATField;
            }
            set {
                this.bLDATField = value;
                this.RaisePropertyChanged("BLDAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string XBLNR {
            get {
                return this.xBLNRField;
            }
            set {
                this.xBLNRField = value;
                this.RaisePropertyChanged("XBLNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string BUDAT {
            get {
                return this.bUDATField;
            }
            set {
                this.bUDATField = value;
                this.RaisePropertyChanged("BUDAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string WAERS {
            get {
                return this.wAERSField;
            }
            set {
                this.wAERSField = value;
                this.RaisePropertyChanged("WAERS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string KURSF {
            get {
                return this.kURSFField;
            }
            set {
                this.kURSFField = value;
                this.RaisePropertyChanged("KURSF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string BKTXT {
            get {
                return this.bKTXTField;
            }
            set {
                this.bKTXTField = value;
                this.RaisePropertyChanged("BKTXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string XREF1_HD {
            get {
                return this.xREF1_HDField;
            }
            set {
                this.xREF1_HDField = value;
                this.RaisePropertyChanged("XREF1_HD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string STGRD {
            get {
                return this.sTGRDField;
            }
            set {
                this.sTGRDField = value;
                this.RaisePropertyChanged("STGRD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string STODT {
            get {
                return this.sTODTField;
            }
            set {
                this.sTODTField = value;
                this.RaisePropertyChanged("STODT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string NEWBS {
            get {
                return this.nEWBSField;
            }
            set {
                this.nEWBSField = value;
                this.RaisePropertyChanged("NEWBS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string NEWUM {
            get {
                return this.nEWUMField;
            }
            set {
                this.nEWUMField = value;
                this.RaisePropertyChanged("NEWUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string LGACC {
            get {
                return this.lGACCField;
            }
            set {
                this.lGACCField = value;
                this.RaisePropertyChanged("LGACC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string ACCOD {
            get {
                return this.aCCODField;
            }
            set {
                this.aCCODField = value;
                this.RaisePropertyChanged("ACCOD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string NEWKO {
            get {
                return this.nEWKOField;
            }
            set {
                this.nEWKOField = value;
                this.RaisePropertyChanged("NEWKO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string ANBWA {
            get {
                return this.aNBWAField;
            }
            set {
                this.aNBWAField = value;
                this.RaisePropertyChanged("ANBWA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string WRBTR {
            get {
                return this.wRBTRField;
            }
            set {
                this.wRBTRField = value;
                this.RaisePropertyChanged("WRBTR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string DMBTR {
            get {
                return this.dMBTRField;
            }
            set {
                this.dMBTRField = value;
                this.RaisePropertyChanged("DMBTR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string SKFBT {
            get {
                return this.sKFBTField;
            }
            set {
                this.sKFBTField = value;
                this.RaisePropertyChanged("SKFBT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string WSKTO {
            get {
                return this.wSKTOField;
            }
            set {
                this.wSKTOField = value;
                this.RaisePropertyChanged("WSKTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string MWSTS {
            get {
                return this.mWSTSField;
            }
            set {
                this.mWSTSField = value;
                this.RaisePropertyChanged("MWSTS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string WMWST {
            get {
                return this.wMWSTField;
            }
            set {
                this.wMWSTField = value;
                this.RaisePropertyChanged("WMWST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string MWSKZ {
            get {
                return this.mWSKZField;
            }
            set {
                this.mWSKZField = value;
                this.RaisePropertyChanged("MWSKZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string ZFBDT {
            get {
                return this.zFBDTField;
            }
            set {
                this.zFBDTField = value;
                this.RaisePropertyChanged("ZFBDT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string ZTERM {
            get {
                return this.zTERMField;
            }
            set {
                this.zTERMField = value;
                this.RaisePropertyChanged("ZTERM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string ZUONR {
            get {
                return this.zUONRField;
            }
            set {
                this.zUONRField = value;
                this.RaisePropertyChanged("ZUONR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string SGTXT {
            get {
                return this.sGTXTField;
            }
            set {
                this.sGTXTField = value;
                this.RaisePropertyChanged("SGTXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string BUPLA {
            get {
                return this.bUPLAField;
            }
            set {
                this.bUPLAField = value;
                this.RaisePropertyChanged("BUPLA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string XREF1 {
            get {
                return this.xREF1Field;
            }
            set {
                this.xREF1Field = value;
                this.RaisePropertyChanged("XREF1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string XREF2 {
            get {
                return this.xREF2Field;
            }
            set {
                this.xREF2Field = value;
                this.RaisePropertyChanged("XREF2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string XREF3 {
            get {
                return this.xREF3Field;
            }
            set {
                this.xREF3Field = value;
                this.RaisePropertyChanged("XREF3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string J_1TPBUPL {
            get {
                return this.j_1TPBUPLField;
            }
            set {
                this.j_1TPBUPLField = value;
                this.RaisePropertyChanged("J_1TPBUPL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string VBUND {
            get {
                return this.vBUNDField;
            }
            set {
                this.vBUNDField = value;
                this.RaisePropertyChanged("VBUND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string NAME1 {
            get {
                return this.nAME1Field;
            }
            set {
                this.nAME1Field = value;
                this.RaisePropertyChanged("NAME1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string NAME2 {
            get {
                return this.nAME2Field;
            }
            set {
                this.nAME2Field = value;
                this.RaisePropertyChanged("NAME2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string NAME3 {
            get {
                return this.nAME3Field;
            }
            set {
                this.nAME3Field = value;
                this.RaisePropertyChanged("NAME3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string NAME4 {
            get {
                return this.nAME4Field;
            }
            set {
                this.nAME4Field = value;
                this.RaisePropertyChanged("NAME4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string STRAS {
            get {
                return this.sTRASField;
            }
            set {
                this.sTRASField = value;
                this.RaisePropertyChanged("STRAS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string ORT01 {
            get {
                return this.oRT01Field;
            }
            set {
                this.oRT01Field = value;
                this.RaisePropertyChanged("ORT01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string PSTLZ {
            get {
                return this.pSTLZField;
            }
            set {
                this.pSTLZField = value;
                this.RaisePropertyChanged("PSTLZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string REGIO {
            get {
                return this.rEGIOField;
            }
            set {
                this.rEGIOField = value;
                this.RaisePropertyChanged("REGIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string LAND1 {
            get {
                return this.lAND1Field;
            }
            set {
                this.lAND1Field = value;
                this.RaisePropertyChanged("LAND1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string STCD3 {
            get {
                return this.sTCD3Field;
            }
            set {
                this.sTCD3Field = value;
                this.RaisePropertyChanged("STCD3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string BANKL {
            get {
                return this.bANKLField;
            }
            set {
                this.bANKLField = value;
                this.RaisePropertyChanged("BANKL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string BANKN {
            get {
                return this.bANKNField;
            }
            set {
                this.bANKNField = value;
                this.RaisePropertyChanged("BANKN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string WITHT1 {
            get {
                return this.wITHT1Field;
            }
            set {
                this.wITHT1Field = value;
                this.RaisePropertyChanged("WITHT1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=49)]
        public string WT_WITHCD1 {
            get {
                return this.wT_WITHCD1Field;
            }
            set {
                this.wT_WITHCD1Field = value;
                this.RaisePropertyChanged("WT_WITHCD1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=50)]
        public string WT_QSSHH1 {
            get {
                return this.wT_QSSHH1Field;
            }
            set {
                this.wT_QSSHH1Field = value;
                this.RaisePropertyChanged("WT_QSSHH1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=51)]
        public string WT_QBSHH1 {
            get {
                return this.wT_QBSHH1Field;
            }
            set {
                this.wT_QBSHH1Field = value;
                this.RaisePropertyChanged("WT_QBSHH1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=52)]
        public string WITHT2 {
            get {
                return this.wITHT2Field;
            }
            set {
                this.wITHT2Field = value;
                this.RaisePropertyChanged("WITHT2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=53)]
        public string WT_WITHCD2 {
            get {
                return this.wT_WITHCD2Field;
            }
            set {
                this.wT_WITHCD2Field = value;
                this.RaisePropertyChanged("WT_WITHCD2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=54)]
        public string WT_QSSHH2 {
            get {
                return this.wT_QSSHH2Field;
            }
            set {
                this.wT_QSSHH2Field = value;
                this.RaisePropertyChanged("WT_QSSHH2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=55)]
        public string WT_QBSHH2 {
            get {
                return this.wT_QBSHH2Field;
            }
            set {
                this.wT_QBSHH2Field = value;
                this.RaisePropertyChanged("WT_QBSHH2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=56)]
        public string WITHT3 {
            get {
                return this.wITHT3Field;
            }
            set {
                this.wITHT3Field = value;
                this.RaisePropertyChanged("WITHT3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=57)]
        public string WT_WITHCD3 {
            get {
                return this.wT_WITHCD3Field;
            }
            set {
                this.wT_WITHCD3Field = value;
                this.RaisePropertyChanged("WT_WITHCD3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=58)]
        public string WT_QSSHH3 {
            get {
                return this.wT_QSSHH3Field;
            }
            set {
                this.wT_QSSHH3Field = value;
                this.RaisePropertyChanged("WT_QSSHH3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=59)]
        public string WT_QBSHH3 {
            get {
                return this.wT_QBSHH3Field;
            }
            set {
                this.wT_QBSHH3Field = value;
                this.RaisePropertyChanged("WT_QBSHH3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=60)]
        public string GSBER {
            get {
                return this.gSBERField;
            }
            set {
                this.gSBERField = value;
                this.RaisePropertyChanged("GSBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=61)]
        public string ZZ01 {
            get {
                return this.zZ01Field;
            }
            set {
                this.zZ01Field = value;
                this.RaisePropertyChanged("ZZ01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=62)]
        public string ZZ02 {
            get {
                return this.zZ02Field;
            }
            set {
                this.zZ02Field = value;
                this.RaisePropertyChanged("ZZ02");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=63)]
        public string PRCTR {
            get {
                return this.pRCTRField;
            }
            set {
                this.pRCTRField = value;
                this.RaisePropertyChanged("PRCTR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=64)]
        public string ZZ03 {
            get {
                return this.zZ03Field;
            }
            set {
                this.zZ03Field = value;
                this.RaisePropertyChanged("ZZ03");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=65)]
        public string KOSTL {
            get {
                return this.kOSTLField;
            }
            set {
                this.kOSTLField = value;
                this.RaisePropertyChanged("KOSTL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=66)]
        public string ZZ04 {
            get {
                return this.zZ04Field;
            }
            set {
                this.zZ04Field = value;
                this.RaisePropertyChanged("ZZ04");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=67)]
        public string ZZ05 {
            get {
                return this.zZ05Field;
            }
            set {
                this.zZ05Field = value;
                this.RaisePropertyChanged("ZZ05");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=68)]
        public string ZZ06 {
            get {
                return this.zZ06Field;
            }
            set {
                this.zZ06Field = value;
                this.RaisePropertyChanged("ZZ06");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=69)]
        public string ZZ07 {
            get {
                return this.zZ07Field;
            }
            set {
                this.zZ07Field = value;
                this.RaisePropertyChanged("ZZ07");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=70)]
        public string AUFNR {
            get {
                return this.aUFNRField;
            }
            set {
                this.aUFNRField = value;
                this.RaisePropertyChanged("AUFNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=71)]
        public string ZZKOSTL {
            get {
                return this.zZKOSTLField;
            }
            set {
                this.zZKOSTLField = value;
                this.RaisePropertyChanged("ZZKOSTL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=72)]
        public string QUNTY {
            get {
                return this.qUNTYField;
            }
            set {
                this.qUNTYField = value;
                this.RaisePropertyChanged("QUNTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=73)]
        public string ANLKL {
            get {
                return this.aNLKLField;
            }
            set {
                this.aNLKLField = value;
                this.RaisePropertyChanged("ANLKL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=74)]
        public string NASSETS {
            get {
                return this.nASSETSField;
            }
            set {
                this.nASSETSField = value;
                this.RaisePropertyChanged("NASSETS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=75)]
        public string DES01 {
            get {
                return this.dES01Field;
            }
            set {
                this.dES01Field = value;
                this.RaisePropertyChanged("DES01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=76)]
        public string DES02 {
            get {
                return this.dES02Field;
            }
            set {
                this.dES02Field = value;
                this.RaisePropertyChanged("DES02");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=77)]
        public string INVNR {
            get {
                return this.iNVNRField;
            }
            set {
                this.iNVNRField = value;
                this.RaisePropertyChanged("INVNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=78)]
        public string MENGE {
            get {
                return this.mENGEField;
            }
            set {
                this.mENGEField = value;
                this.RaisePropertyChanged("MENGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=79)]
        public string MEINS {
            get {
                return this.mEINSField;
            }
            set {
                this.mEINSField = value;
                this.RaisePropertyChanged("MEINS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=80)]
        public string INKEN {
            get {
                return this.iNKENField;
            }
            set {
                this.iNKENField = value;
                this.RaisePropertyChanged("INKEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=81)]
        public string KOSTLM {
            get {
                return this.kOSTLMField;
            }
            set {
                this.kOSTLMField = value;
                this.RaisePropertyChanged("KOSTLM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=82)]
        public string KOSTLV {
            get {
                return this.kOSTLVField;
            }
            set {
                this.kOSTLVField = value;
                this.RaisePropertyChanged("KOSTLV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=83)]
        public string CAUFN {
            get {
                return this.cAUFNField;
            }
            set {
                this.cAUFNField = value;
                this.RaisePropertyChanged("CAUFN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=84)]
        public string SEGMENT {
            get {
                return this.sEGMENTField;
            }
            set {
                this.sEGMENTField = value;
                this.RaisePropertyChanged("SEGMENT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=85)]
        public string ORD41 {
            get {
                return this.oRD41Field;
            }
            set {
                this.oRD41Field = value;
                this.RaisePropertyChanged("ORD41");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=86)]
        public string GDLGRP {
            get {
                return this.gDLGRPField;
            }
            set {
                this.gDLGRPField = value;
                this.RaisePropertyChanged("GDLGRP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=87)]
        public string TYPBZ {
            get {
                return this.tYPBZField;
            }
            set {
                this.tYPBZField = value;
                this.RaisePropertyChanged("TYPBZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=88)]
        public string PUBTR {
            get {
                return this.pUBTRField;
            }
            set {
                this.pUBTRField = value;
                this.RaisePropertyChanged("PUBTR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=89)]
        public string TPBTR {
            get {
                return this.tPBTRField;
            }
            set {
                this.tPBTRField = value;
                this.RaisePropertyChanged("TPBTR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=90)]
        public string BELNR {
            get {
                return this.bELNRField;
            }
            set {
                this.bELNRField = value;
                this.RaisePropertyChanged("BELNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=91)]
        public string GJAHR {
            get {
                return this.gJAHRField;
            }
            set {
                this.gJAHRField = value;
                this.RaisePropertyChanged("GJAHR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=92)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=93)]
        public string CODE {
            get {
                return this.cODEField;
            }
            set {
                this.cODEField = value;
                this.RaisePropertyChanged("CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=94)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:thailife.com:ACT:AA:AAI001")]
    public partial class DT_RTN_AAI001_SNDItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rEFERENCE1Field;
        
        private string iNVENT_NUMBERField;
        
        private string aSSET_TYPE_NAMEField;
        
        private string cOMPANY_CODEField;
        
        private string dOC_NUMBERField;
        
        private string fISCAL_YEARField;
        
        private string aSSET_NOField;
        
        private string sUB_NUMBERField;
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        private string pARAMETERField;
        
        private string rOWField;
        
        private string fIELDField;
        
        private string sYSTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string REFERENCE1 {
            get {
                return this.rEFERENCE1Field;
            }
            set {
                this.rEFERENCE1Field = value;
                this.RaisePropertyChanged("REFERENCE1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string INVENT_NUMBER {
            get {
                return this.iNVENT_NUMBERField;
            }
            set {
                this.iNVENT_NUMBERField = value;
                this.RaisePropertyChanged("INVENT_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ASSET_TYPE_NAME {
            get {
                return this.aSSET_TYPE_NAMEField;
            }
            set {
                this.aSSET_TYPE_NAMEField = value;
                this.RaisePropertyChanged("ASSET_TYPE_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string COMPANY_CODE {
            get {
                return this.cOMPANY_CODEField;
            }
            set {
                this.cOMPANY_CODEField = value;
                this.RaisePropertyChanged("COMPANY_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DOC_NUMBER {
            get {
                return this.dOC_NUMBERField;
            }
            set {
                this.dOC_NUMBERField = value;
                this.RaisePropertyChanged("DOC_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string FISCAL_YEAR {
            get {
                return this.fISCAL_YEARField;
            }
            set {
                this.fISCAL_YEARField = value;
                this.RaisePropertyChanged("FISCAL_YEAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ASSET_NO {
            get {
                return this.aSSET_NOField;
            }
            set {
                this.aSSET_NOField = value;
                this.RaisePropertyChanged("ASSET_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string SUB_NUMBER {
            get {
                return this.sUB_NUMBERField;
            }
            set {
                this.sUB_NUMBERField = value;
                this.RaisePropertyChanged("SUB_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
                this.RaisePropertyChanged("NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string LOG_NO {
            get {
                return this.lOG_NOField;
            }
            set {
                this.lOG_NOField = value;
                this.RaisePropertyChanged("LOG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string LOG_MSG_NO {
            get {
                return this.lOG_MSG_NOField;
            }
            set {
                this.lOG_MSG_NOField = value;
                this.RaisePropertyChanged("LOG_MSG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string MESSAGE_V1 {
            get {
                return this.mESSAGE_V1Field;
            }
            set {
                this.mESSAGE_V1Field = value;
                this.RaisePropertyChanged("MESSAGE_V1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string MESSAGE_V2 {
            get {
                return this.mESSAGE_V2Field;
            }
            set {
                this.mESSAGE_V2Field = value;
                this.RaisePropertyChanged("MESSAGE_V2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string MESSAGE_V3 {
            get {
                return this.mESSAGE_V3Field;
            }
            set {
                this.mESSAGE_V3Field = value;
                this.RaisePropertyChanged("MESSAGE_V3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string MESSAGE_V4 {
            get {
                return this.mESSAGE_V4Field;
            }
            set {
                this.mESSAGE_V4Field = value;
                this.RaisePropertyChanged("MESSAGE_V4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string PARAMETER {
            get {
                return this.pARAMETERField;
            }
            set {
                this.pARAMETERField = value;
                this.RaisePropertyChanged("PARAMETER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=19)]
        public string ROW {
            get {
                return this.rOWField;
            }
            set {
                this.rOWField = value;
                this.RaisePropertyChanged("ROW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string FIELD {
            get {
                return this.fIELDField;
            }
            set {
                this.fIELDField = value;
                this.RaisePropertyChanged("FIELD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string SYSTEM {
            get {
                return this.sYSTEMField;
            }
            set {
                this.sYSTEMField = value;
                this.RaisePropertyChanged("SYSTEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_TLI_PurchaseOnline_SYNC_SNDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:thailife.com:ACT:AA:AAI001", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("row", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AddonProcurement.GRServiceReference.DT_TLI_AAI001_SNDRow[] MT_TLI_AAI001_SND;
        
        public SI_TLI_PurchaseOnline_SYNC_SNDRequest() {
        }
        
        public SI_TLI_PurchaseOnline_SYNC_SNDRequest(AddonProcurement.GRServiceReference.DT_TLI_AAI001_SNDRow[] MT_TLI_AAI001_SND) {
            this.MT_TLI_AAI001_SND = MT_TLI_AAI001_SND;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_TLI_PurchaseOnline_SYNC_SNDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:thailife.com:ACT:AA:AAI001", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AddonProcurement.GRServiceReference.DT_RTN_AAI001_SNDItem[] MT_RTN_AAI001_SND;
        
        public SI_TLI_PurchaseOnline_SYNC_SNDResponse() {
        }
        
        public SI_TLI_PurchaseOnline_SYNC_SNDResponse(AddonProcurement.GRServiceReference.DT_RTN_AAI001_SNDItem[] MT_RTN_AAI001_SND) {
            this.MT_RTN_AAI001_SND = MT_RTN_AAI001_SND;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_TLI_PurchaseOnline_SYNC_SNDChannel : AddonProcurement.GRServiceReference.SI_TLI_PurchaseOnline_SYNC_SND, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_TLI_PurchaseOnline_SYNC_SNDClient : System.ServiceModel.ClientBase<AddonProcurement.GRServiceReference.SI_TLI_PurchaseOnline_SYNC_SND>, AddonProcurement.GRServiceReference.SI_TLI_PurchaseOnline_SYNC_SND {
        
        public SI_TLI_PurchaseOnline_SYNC_SNDClient() {
        }
        
        public SI_TLI_PurchaseOnline_SYNC_SNDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_TLI_PurchaseOnline_SYNC_SNDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_TLI_PurchaseOnline_SYNC_SNDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_TLI_PurchaseOnline_SYNC_SNDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AddonProcurement.GRServiceReference.SI_TLI_PurchaseOnline_SYNC_SNDResponse AddonProcurement.GRServiceReference.SI_TLI_PurchaseOnline_SYNC_SND.SI_TLI_PurchaseOnline_SYNC_SND(AddonProcurement.GRServiceReference.SI_TLI_PurchaseOnline_SYNC_SNDRequest request) {
            return base.Channel.SI_TLI_PurchaseOnline_SYNC_SND(request);
        }
        
        public AddonProcurement.GRServiceReference.DT_RTN_AAI001_SNDItem[] SI_TLI_PurchaseOnline_SYNC_SND(AddonProcurement.GRServiceReference.DT_TLI_AAI001_SNDRow[] MT_TLI_AAI001_SND) {
            AddonProcurement.GRServiceReference.SI_TLI_PurchaseOnline_SYNC_SNDRequest inValue = new AddonProcurement.GRServiceReference.SI_TLI_PurchaseOnline_SYNC_SNDRequest();
            inValue.MT_TLI_AAI001_SND = MT_TLI_AAI001_SND;
            AddonProcurement.GRServiceReference.SI_TLI_PurchaseOnline_SYNC_SNDResponse retVal = ((AddonProcurement.GRServiceReference.SI_TLI_PurchaseOnline_SYNC_SND)(this)).SI_TLI_PurchaseOnline_SYNC_SND(inValue);
            return retVal.MT_RTN_AAI001_SND;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AddonProcurement.GRServiceReference.SI_TLI_PurchaseOnline_SYNC_SNDResponse> AddonProcurement.GRServiceReference.SI_TLI_PurchaseOnline_SYNC_SND.SI_TLI_PurchaseOnline_SYNC_SNDAsync(AddonProcurement.GRServiceReference.SI_TLI_PurchaseOnline_SYNC_SNDRequest request) {
            return base.Channel.SI_TLI_PurchaseOnline_SYNC_SNDAsync(request);
        }
        
        public System.Threading.Tasks.Task<AddonProcurement.GRServiceReference.SI_TLI_PurchaseOnline_SYNC_SNDResponse> SI_TLI_PurchaseOnline_SYNC_SNDAsync(AddonProcurement.GRServiceReference.DT_TLI_AAI001_SNDRow[] MT_TLI_AAI001_SND) {
            AddonProcurement.GRServiceReference.SI_TLI_PurchaseOnline_SYNC_SNDRequest inValue = new AddonProcurement.GRServiceReference.SI_TLI_PurchaseOnline_SYNC_SNDRequest();
            inValue.MT_TLI_AAI001_SND = MT_TLI_AAI001_SND;
            return ((AddonProcurement.GRServiceReference.SI_TLI_PurchaseOnline_SYNC_SND)(this)).SI_TLI_PurchaseOnline_SYNC_SNDAsync(inValue);
        }
    }
}
