//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddonProcurement.SRMIInterfaceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="POinterfacex", Namespace="http://schemas.datacontract.org/2004/07/SRMIInterface")]
    [System.SerializableAttribute()]
    public partial class POinterfacex : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthenkeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AddonProcurement.SRMIInterfaceReference.POinterface[] POinterfacesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Authenkey {
            get {
                return this.AuthenkeyField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenkeyField, value) != true)) {
                    this.AuthenkeyField = value;
                    this.RaisePropertyChanged("Authenkey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AddonProcurement.SRMIInterfaceReference.POinterface[] POinterfaces {
            get {
                return this.POinterfacesField;
            }
            set {
                if ((object.ReferenceEquals(this.POinterfacesField, value) != true)) {
                    this.POinterfacesField = value;
                    this.RaisePropertyChanged("POinterfaces");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="POinterface", Namespace="http://schemas.datacontract.org/2004/07/SRMIInterface")]
    [System.SerializableAttribute()]
    public partial class POinterface : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AddonProcurement.SRMIInterfaceReference.PO_AccAssignment[] AccAssignmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AddonProcurement.SRMIInterfaceReference.PO_CondHeader[] CondHeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AddonProcurement.SRMIInterfaceReference.PO_CondItem[] CondItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AddonProcurement.SRMIInterfaceReference.PO_Header HeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AddonProcurement.SRMIInterfaceReference.PO_Item[] ItemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AddonProcurement.SRMIInterfaceReference.PO_AccAssignment[] AccAssignment {
            get {
                return this.AccAssignmentField;
            }
            set {
                if ((object.ReferenceEquals(this.AccAssignmentField, value) != true)) {
                    this.AccAssignmentField = value;
                    this.RaisePropertyChanged("AccAssignment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AddonProcurement.SRMIInterfaceReference.PO_CondHeader[] CondHeader {
            get {
                return this.CondHeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.CondHeaderField, value) != true)) {
                    this.CondHeaderField = value;
                    this.RaisePropertyChanged("CondHeader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AddonProcurement.SRMIInterfaceReference.PO_CondItem[] CondItem {
            get {
                return this.CondItemField;
            }
            set {
                if ((object.ReferenceEquals(this.CondItemField, value) != true)) {
                    this.CondItemField = value;
                    this.RaisePropertyChanged("CondItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AddonProcurement.SRMIInterfaceReference.PO_Header Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AddonProcurement.SRMIInterfaceReference.PO_Item[] Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PO_Header", Namespace="http://schemas.datacontract.org/2004/07/SRMIInterface")]
    [System.SerializableAttribute()]
    public partial class PO_Header : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_COM_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_COM_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_CREATE_BYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_CURRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_CURR_LEVELField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_DOC_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_EXCHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_HEADER_NOTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_INCOTERMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_INCOTERM_DESCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_PAYMENT_TERMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_PAYMENT_TERM_DESCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_PUR_GRPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_PUR_ORGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_REL1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_REL_TXT1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_TOTALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_TYPE_DESCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_VENDORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_VENDOR_EMAILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_VENDOR_EXTENSIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_VENDOR_FAXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_VENDOR_NAMEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_COM_CODE {
            get {
                return this.PO_COM_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_COM_CODEField, value) != true)) {
                    this.PO_COM_CODEField = value;
                    this.RaisePropertyChanged("PO_COM_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_COM_NAME {
            get {
                return this.PO_COM_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_COM_NAMEField, value) != true)) {
                    this.PO_COM_NAMEField = value;
                    this.RaisePropertyChanged("PO_COM_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_CREATE_BY {
            get {
                return this.PO_CREATE_BYField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_CREATE_BYField, value) != true)) {
                    this.PO_CREATE_BYField = value;
                    this.RaisePropertyChanged("PO_CREATE_BY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_CURR {
            get {
                return this.PO_CURRField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_CURRField, value) != true)) {
                    this.PO_CURRField = value;
                    this.RaisePropertyChanged("PO_CURR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_CURR_LEVEL {
            get {
                return this.PO_CURR_LEVELField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_CURR_LEVELField, value) != true)) {
                    this.PO_CURR_LEVELField = value;
                    this.RaisePropertyChanged("PO_CURR_LEVEL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_DOC_DATE {
            get {
                return this.PO_DOC_DATEField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_DOC_DATEField, value) != true)) {
                    this.PO_DOC_DATEField = value;
                    this.RaisePropertyChanged("PO_DOC_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_EXCH {
            get {
                return this.PO_EXCHField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_EXCHField, value) != true)) {
                    this.PO_EXCHField = value;
                    this.RaisePropertyChanged("PO_EXCH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_HEADER_NOTE {
            get {
                return this.PO_HEADER_NOTEField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_HEADER_NOTEField, value) != true)) {
                    this.PO_HEADER_NOTEField = value;
                    this.RaisePropertyChanged("PO_HEADER_NOTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_INCOTERM {
            get {
                return this.PO_INCOTERMField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_INCOTERMField, value) != true)) {
                    this.PO_INCOTERMField = value;
                    this.RaisePropertyChanged("PO_INCOTERM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_INCOTERM_DESC {
            get {
                return this.PO_INCOTERM_DESCField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_INCOTERM_DESCField, value) != true)) {
                    this.PO_INCOTERM_DESCField = value;
                    this.RaisePropertyChanged("PO_INCOTERM_DESC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_NO {
            get {
                return this.PO_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_NOField, value) != true)) {
                    this.PO_NOField = value;
                    this.RaisePropertyChanged("PO_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_PAYMENT_TERM {
            get {
                return this.PO_PAYMENT_TERMField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_PAYMENT_TERMField, value) != true)) {
                    this.PO_PAYMENT_TERMField = value;
                    this.RaisePropertyChanged("PO_PAYMENT_TERM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_PAYMENT_TERM_DESC {
            get {
                return this.PO_PAYMENT_TERM_DESCField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_PAYMENT_TERM_DESCField, value) != true)) {
                    this.PO_PAYMENT_TERM_DESCField = value;
                    this.RaisePropertyChanged("PO_PAYMENT_TERM_DESC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_PUR_GRP {
            get {
                return this.PO_PUR_GRPField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_PUR_GRPField, value) != true)) {
                    this.PO_PUR_GRPField = value;
                    this.RaisePropertyChanged("PO_PUR_GRP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_PUR_ORG {
            get {
                return this.PO_PUR_ORGField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_PUR_ORGField, value) != true)) {
                    this.PO_PUR_ORGField = value;
                    this.RaisePropertyChanged("PO_PUR_ORG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_REL1 {
            get {
                return this.PO_REL1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PO_REL1Field, value) != true)) {
                    this.PO_REL1Field = value;
                    this.RaisePropertyChanged("PO_REL1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_REL_TXT1 {
            get {
                return this.PO_REL_TXT1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PO_REL_TXT1Field, value) != true)) {
                    this.PO_REL_TXT1Field = value;
                    this.RaisePropertyChanged("PO_REL_TXT1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_TOTAL {
            get {
                return this.PO_TOTALField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_TOTALField, value) != true)) {
                    this.PO_TOTALField = value;
                    this.RaisePropertyChanged("PO_TOTAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_TYPE {
            get {
                return this.PO_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_TYPEField, value) != true)) {
                    this.PO_TYPEField = value;
                    this.RaisePropertyChanged("PO_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_TYPE_DESC {
            get {
                return this.PO_TYPE_DESCField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_TYPE_DESCField, value) != true)) {
                    this.PO_TYPE_DESCField = value;
                    this.RaisePropertyChanged("PO_TYPE_DESC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_VENDOR {
            get {
                return this.PO_VENDORField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_VENDORField, value) != true)) {
                    this.PO_VENDORField = value;
                    this.RaisePropertyChanged("PO_VENDOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_VENDOR_EMAIL {
            get {
                return this.PO_VENDOR_EMAILField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_VENDOR_EMAILField, value) != true)) {
                    this.PO_VENDOR_EMAILField = value;
                    this.RaisePropertyChanged("PO_VENDOR_EMAIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_VENDOR_EXTENSION {
            get {
                return this.PO_VENDOR_EXTENSIONField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_VENDOR_EXTENSIONField, value) != true)) {
                    this.PO_VENDOR_EXTENSIONField = value;
                    this.RaisePropertyChanged("PO_VENDOR_EXTENSION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_VENDOR_FAX {
            get {
                return this.PO_VENDOR_FAXField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_VENDOR_FAXField, value) != true)) {
                    this.PO_VENDOR_FAXField = value;
                    this.RaisePropertyChanged("PO_VENDOR_FAX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_VENDOR_NAME {
            get {
                return this.PO_VENDOR_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_VENDOR_NAMEField, value) != true)) {
                    this.PO_VENDOR_NAMEField = value;
                    this.RaisePropertyChanged("PO_VENDOR_NAME");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PO_AccAssignment", Namespace="http://schemas.datacontract.org/2004/07/SRMIInterface")]
    [System.SerializableAttribute()]
    public partial class PO_AccAssignment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_ASSETSUB_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_ASSET_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_BA_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_COST_CTR_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_GL_ACC_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_ITEM_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_ORDER_NOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_ASSETSUB_NO {
            get {
                return this.PO_ASSETSUB_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_ASSETSUB_NOField, value) != true)) {
                    this.PO_ASSETSUB_NOField = value;
                    this.RaisePropertyChanged("PO_ASSETSUB_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_ASSET_NO {
            get {
                return this.PO_ASSET_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_ASSET_NOField, value) != true)) {
                    this.PO_ASSET_NOField = value;
                    this.RaisePropertyChanged("PO_ASSET_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_BA_NO {
            get {
                return this.PO_BA_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_BA_NOField, value) != true)) {
                    this.PO_BA_NOField = value;
                    this.RaisePropertyChanged("PO_BA_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_COST_CTR_NO {
            get {
                return this.PO_COST_CTR_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_COST_CTR_NOField, value) != true)) {
                    this.PO_COST_CTR_NOField = value;
                    this.RaisePropertyChanged("PO_COST_CTR_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_GL_ACC_NO {
            get {
                return this.PO_GL_ACC_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_GL_ACC_NOField, value) != true)) {
                    this.PO_GL_ACC_NOField = value;
                    this.RaisePropertyChanged("PO_GL_ACC_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_ITEM_NO {
            get {
                return this.PO_ITEM_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_ITEM_NOField, value) != true)) {
                    this.PO_ITEM_NOField = value;
                    this.RaisePropertyChanged("PO_ITEM_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_NO {
            get {
                return this.PO_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_NOField, value) != true)) {
                    this.PO_NOField = value;
                    this.RaisePropertyChanged("PO_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_ORDER_NO {
            get {
                return this.PO_ORDER_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_ORDER_NOField, value) != true)) {
                    this.PO_ORDER_NOField = value;
                    this.RaisePropertyChanged("PO_ORDER_NO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PO_CondHeader", Namespace="http://schemas.datacontract.org/2004/07/SRMIInterface")]
    [System.SerializableAttribute()]
    public partial class PO_CondHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_COND_CURRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_COND_RTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_COND_TPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_COND_VENField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_COND_CURR {
            get {
                return this.PO_COND_CURRField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_COND_CURRField, value) != true)) {
                    this.PO_COND_CURRField = value;
                    this.RaisePropertyChanged("PO_COND_CURR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_COND_RT {
            get {
                return this.PO_COND_RTField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_COND_RTField, value) != true)) {
                    this.PO_COND_RTField = value;
                    this.RaisePropertyChanged("PO_COND_RT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_COND_TP {
            get {
                return this.PO_COND_TPField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_COND_TPField, value) != true)) {
                    this.PO_COND_TPField = value;
                    this.RaisePropertyChanged("PO_COND_TP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_COND_VEN {
            get {
                return this.PO_COND_VENField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_COND_VENField, value) != true)) {
                    this.PO_COND_VENField = value;
                    this.RaisePropertyChanged("PO_COND_VEN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PO_CondItem", Namespace="http://schemas.datacontract.org/2004/07/SRMIInterface")]
    [System.SerializableAttribute()]
    public partial class PO_CondItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_COND_CURRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_COND_ITEMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_COND_PRC_UNITField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_COND_RTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_COND_TPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_COND_UNITField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_COND_VENField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_COND_CURR {
            get {
                return this.PO_COND_CURRField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_COND_CURRField, value) != true)) {
                    this.PO_COND_CURRField = value;
                    this.RaisePropertyChanged("PO_COND_CURR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_COND_ITEM {
            get {
                return this.PO_COND_ITEMField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_COND_ITEMField, value) != true)) {
                    this.PO_COND_ITEMField = value;
                    this.RaisePropertyChanged("PO_COND_ITEM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_COND_PRC_UNIT {
            get {
                return this.PO_COND_PRC_UNITField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_COND_PRC_UNITField, value) != true)) {
                    this.PO_COND_PRC_UNITField = value;
                    this.RaisePropertyChanged("PO_COND_PRC_UNIT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_COND_RT {
            get {
                return this.PO_COND_RTField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_COND_RTField, value) != true)) {
                    this.PO_COND_RTField = value;
                    this.RaisePropertyChanged("PO_COND_RT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_COND_TP {
            get {
                return this.PO_COND_TPField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_COND_TPField, value) != true)) {
                    this.PO_COND_TPField = value;
                    this.RaisePropertyChanged("PO_COND_TP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_COND_UNIT {
            get {
                return this.PO_COND_UNITField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_COND_UNITField, value) != true)) {
                    this.PO_COND_UNITField = value;
                    this.RaisePropertyChanged("PO_COND_UNIT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_COND_VEN {
            get {
                return this.PO_COND_VENField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_COND_VENField, value) != true)) {
                    this.PO_COND_VENField = value;
                    this.RaisePropertyChanged("PO_COND_VEN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PO_Item", Namespace="http://schemas.datacontract.org/2004/07/SRMIInterface")]
    [System.SerializableAttribute()]
    public partial class PO_Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_ACC_CATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_CONV_OPUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_CONV_OUNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_DELIVERY_COMPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_DEL_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_DEL_INDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_FINAL_INVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_ITEM_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_MAT_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_MAT_SHORT_TXTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_NET_PRICEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_NET_VELUEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_ORDER_UNITField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_PLANTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_PLANT_DESCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_QTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_TAXCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PR_ITEM_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PR_NOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_ACC_CAT {
            get {
                return this.PO_ACC_CATField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_ACC_CATField, value) != true)) {
                    this.PO_ACC_CATField = value;
                    this.RaisePropertyChanged("PO_ACC_CAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_CONV_OPU {
            get {
                return this.PO_CONV_OPUField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_CONV_OPUField, value) != true)) {
                    this.PO_CONV_OPUField = value;
                    this.RaisePropertyChanged("PO_CONV_OPU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_CONV_OUN {
            get {
                return this.PO_CONV_OUNField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_CONV_OUNField, value) != true)) {
                    this.PO_CONV_OUNField = value;
                    this.RaisePropertyChanged("PO_CONV_OUN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_DELIVERY_COMP {
            get {
                return this.PO_DELIVERY_COMPField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_DELIVERY_COMPField, value) != true)) {
                    this.PO_DELIVERY_COMPField = value;
                    this.RaisePropertyChanged("PO_DELIVERY_COMP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_DEL_DATE {
            get {
                return this.PO_DEL_DATEField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_DEL_DATEField, value) != true)) {
                    this.PO_DEL_DATEField = value;
                    this.RaisePropertyChanged("PO_DEL_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_DEL_IND {
            get {
                return this.PO_DEL_INDField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_DEL_INDField, value) != true)) {
                    this.PO_DEL_INDField = value;
                    this.RaisePropertyChanged("PO_DEL_IND");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_FINAL_INV {
            get {
                return this.PO_FINAL_INVField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_FINAL_INVField, value) != true)) {
                    this.PO_FINAL_INVField = value;
                    this.RaisePropertyChanged("PO_FINAL_INV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_ITEM_NO {
            get {
                return this.PO_ITEM_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_ITEM_NOField, value) != true)) {
                    this.PO_ITEM_NOField = value;
                    this.RaisePropertyChanged("PO_ITEM_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_MAT_NO {
            get {
                return this.PO_MAT_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_MAT_NOField, value) != true)) {
                    this.PO_MAT_NOField = value;
                    this.RaisePropertyChanged("PO_MAT_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_MAT_SHORT_TXT {
            get {
                return this.PO_MAT_SHORT_TXTField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_MAT_SHORT_TXTField, value) != true)) {
                    this.PO_MAT_SHORT_TXTField = value;
                    this.RaisePropertyChanged("PO_MAT_SHORT_TXT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_NET_PRICE {
            get {
                return this.PO_NET_PRICEField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_NET_PRICEField, value) != true)) {
                    this.PO_NET_PRICEField = value;
                    this.RaisePropertyChanged("PO_NET_PRICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_NET_VELUE {
            get {
                return this.PO_NET_VELUEField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_NET_VELUEField, value) != true)) {
                    this.PO_NET_VELUEField = value;
                    this.RaisePropertyChanged("PO_NET_VELUE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_ORDER_UNIT {
            get {
                return this.PO_ORDER_UNITField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_ORDER_UNITField, value) != true)) {
                    this.PO_ORDER_UNITField = value;
                    this.RaisePropertyChanged("PO_ORDER_UNIT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_PLANT {
            get {
                return this.PO_PLANTField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_PLANTField, value) != true)) {
                    this.PO_PLANTField = value;
                    this.RaisePropertyChanged("PO_PLANT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_PLANT_DESC {
            get {
                return this.PO_PLANT_DESCField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_PLANT_DESCField, value) != true)) {
                    this.PO_PLANT_DESCField = value;
                    this.RaisePropertyChanged("PO_PLANT_DESC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_QTY {
            get {
                return this.PO_QTYField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_QTYField, value) != true)) {
                    this.PO_QTYField = value;
                    this.RaisePropertyChanged("PO_QTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_TAXCODE {
            get {
                return this.PO_TAXCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_TAXCODEField, value) != true)) {
                    this.PO_TAXCODEField = value;
                    this.RaisePropertyChanged("PO_TAXCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PR_ITEM_NO {
            get {
                return this.PR_ITEM_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PR_ITEM_NOField, value) != true)) {
                    this.PR_ITEM_NOField = value;
                    this.RaisePropertyChanged("PR_ITEM_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PR_NO {
            get {
                return this.PR_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PR_NOField, value) != true)) {
                    this.PR_NOField = value;
                    this.RaisePropertyChanged("PR_NO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InterfaceResult", Namespace="http://schemas.datacontract.org/2004/07/SRMIInterface")]
    [System.SerializableAttribute()]
    public partial class InterfaceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EKKO_EBELNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TYPEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EKKO_EBELN {
            get {
                return this.EKKO_EBELNField;
            }
            set {
                if ((object.ReferenceEquals(this.EKKO_EBELNField, value) != true)) {
                    this.EKKO_EBELNField = value;
                    this.RaisePropertyChanged("EKKO_EBELN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TYPE {
            get {
                return this.TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.TYPEField, value) != true)) {
                    this.TYPEField = value;
                    this.RaisePropertyChanged("TYPE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DOInterfacex", Namespace="http://schemas.datacontract.org/2004/07/SRMIInterface")]
    [System.SerializableAttribute()]
    public partial class DOInterfacex : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthenkeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AddonProcurement.SRMIInterfaceReference.DOInterface[] DOInterfacesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Authenkey {
            get {
                return this.AuthenkeyField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenkeyField, value) != true)) {
                    this.AuthenkeyField = value;
                    this.RaisePropertyChanged("Authenkey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AddonProcurement.SRMIInterfaceReference.DOInterface[] DOInterfaces {
            get {
                return this.DOInterfacesField;
            }
            set {
                if ((object.ReferenceEquals(this.DOInterfacesField, value) != true)) {
                    this.DOInterfacesField = value;
                    this.RaisePropertyChanged("DOInterfaces");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DOInterface", Namespace="http://schemas.datacontract.org/2004/07/SRMIInterface")]
    [System.SerializableAttribute()]
    public partial class DOInterface : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AddonProcurement.SRMIInterfaceReference.DO_Header DOHeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AddonProcurement.SRMIInterfaceReference.DO_Item[] DoItemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AddonProcurement.SRMIInterfaceReference.DO_Header DOHeader {
            get {
                return this.DOHeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.DOHeaderField, value) != true)) {
                    this.DOHeaderField = value;
                    this.RaisePropertyChanged("DOHeader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AddonProcurement.SRMIInterfaceReference.DO_Item[] DoItem {
            get {
                return this.DoItemField;
            }
            set {
                if ((object.ReferenceEquals(this.DoItemField, value) != true)) {
                    this.DoItemField = value;
                    this.RaisePropertyChanged("DoItem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DO_Header", Namespace="http://schemas.datacontract.org/2004/07/SRMIInterface")]
    [System.SerializableAttribute()]
    public partial class DO_Header : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_ACT_GM_DTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_CANCELField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_COM_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_CREATE_BYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_CREATE_TMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_DLVY_DTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_DLVY_TYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_DOC_DTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_TRNSP_GRPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_VENDORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_VENDOR_TRANField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_ACT_GM_DT {
            get {
                return this.DO_ACT_GM_DTField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_ACT_GM_DTField, value) != true)) {
                    this.DO_ACT_GM_DTField = value;
                    this.RaisePropertyChanged("DO_ACT_GM_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_CANCEL {
            get {
                return this.DO_CANCELField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_CANCELField, value) != true)) {
                    this.DO_CANCELField = value;
                    this.RaisePropertyChanged("DO_CANCEL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_COM_CODE {
            get {
                return this.DO_COM_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_COM_CODEField, value) != true)) {
                    this.DO_COM_CODEField = value;
                    this.RaisePropertyChanged("DO_COM_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_CREATE_BY {
            get {
                return this.DO_CREATE_BYField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_CREATE_BYField, value) != true)) {
                    this.DO_CREATE_BYField = value;
                    this.RaisePropertyChanged("DO_CREATE_BY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_CREATE_TM {
            get {
                return this.DO_CREATE_TMField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_CREATE_TMField, value) != true)) {
                    this.DO_CREATE_TMField = value;
                    this.RaisePropertyChanged("DO_CREATE_TM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_DLVY_DT {
            get {
                return this.DO_DLVY_DTField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_DLVY_DTField, value) != true)) {
                    this.DO_DLVY_DTField = value;
                    this.RaisePropertyChanged("DO_DLVY_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_DLVY_TY {
            get {
                return this.DO_DLVY_TYField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_DLVY_TYField, value) != true)) {
                    this.DO_DLVY_TYField = value;
                    this.RaisePropertyChanged("DO_DLVY_TY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_DOC_DT {
            get {
                return this.DO_DOC_DTField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_DOC_DTField, value) != true)) {
                    this.DO_DOC_DTField = value;
                    this.RaisePropertyChanged("DO_DOC_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_NO {
            get {
                return this.DO_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_NOField, value) != true)) {
                    this.DO_NOField = value;
                    this.RaisePropertyChanged("DO_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_TRNSP_GRP {
            get {
                return this.DO_TRNSP_GRPField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_TRNSP_GRPField, value) != true)) {
                    this.DO_TRNSP_GRPField = value;
                    this.RaisePropertyChanged("DO_TRNSP_GRP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_VENDOR {
            get {
                return this.DO_VENDORField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_VENDORField, value) != true)) {
                    this.DO_VENDORField = value;
                    this.RaisePropertyChanged("DO_VENDOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_VENDOR_TRAN {
            get {
                return this.DO_VENDOR_TRANField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_VENDOR_TRANField, value) != true)) {
                    this.DO_VENDOR_TRANField = value;
                    this.RaisePropertyChanged("DO_VENDOR_TRAN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DO_Item", Namespace="http://schemas.datacontract.org/2004/07/SRMIInterface")]
    [System.SerializableAttribute()]
    public partial class DO_Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_BATCHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_ITM_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_MATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_MAT_GRPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_MAT_TEXTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_OVER_TOLERANCEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_PLANTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_PO_ITEMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_PO_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_QTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_SLOCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_UNDER_TOLERANCEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DO_UOMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_BATCH {
            get {
                return this.DO_BATCHField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_BATCHField, value) != true)) {
                    this.DO_BATCHField = value;
                    this.RaisePropertyChanged("DO_BATCH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_ITM_NO {
            get {
                return this.DO_ITM_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_ITM_NOField, value) != true)) {
                    this.DO_ITM_NOField = value;
                    this.RaisePropertyChanged("DO_ITM_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_MAT {
            get {
                return this.DO_MATField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_MATField, value) != true)) {
                    this.DO_MATField = value;
                    this.RaisePropertyChanged("DO_MAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_MAT_GRP {
            get {
                return this.DO_MAT_GRPField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_MAT_GRPField, value) != true)) {
                    this.DO_MAT_GRPField = value;
                    this.RaisePropertyChanged("DO_MAT_GRP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_MAT_TEXT {
            get {
                return this.DO_MAT_TEXTField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_MAT_TEXTField, value) != true)) {
                    this.DO_MAT_TEXTField = value;
                    this.RaisePropertyChanged("DO_MAT_TEXT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_OVER_TOLERANCE {
            get {
                return this.DO_OVER_TOLERANCEField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_OVER_TOLERANCEField, value) != true)) {
                    this.DO_OVER_TOLERANCEField = value;
                    this.RaisePropertyChanged("DO_OVER_TOLERANCE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_PLANT {
            get {
                return this.DO_PLANTField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_PLANTField, value) != true)) {
                    this.DO_PLANTField = value;
                    this.RaisePropertyChanged("DO_PLANT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_PO_ITEM {
            get {
                return this.DO_PO_ITEMField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_PO_ITEMField, value) != true)) {
                    this.DO_PO_ITEMField = value;
                    this.RaisePropertyChanged("DO_PO_ITEM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_PO_NO {
            get {
                return this.DO_PO_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_PO_NOField, value) != true)) {
                    this.DO_PO_NOField = value;
                    this.RaisePropertyChanged("DO_PO_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_QTY {
            get {
                return this.DO_QTYField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_QTYField, value) != true)) {
                    this.DO_QTYField = value;
                    this.RaisePropertyChanged("DO_QTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_SLOC {
            get {
                return this.DO_SLOCField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_SLOCField, value) != true)) {
                    this.DO_SLOCField = value;
                    this.RaisePropertyChanged("DO_SLOC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_UNDER_TOLERANCE {
            get {
                return this.DO_UNDER_TOLERANCEField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_UNDER_TOLERANCEField, value) != true)) {
                    this.DO_UNDER_TOLERANCEField = value;
                    this.RaisePropertyChanged("DO_UNDER_TOLERANCE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DO_UOM {
            get {
                return this.DO_UOMField;
            }
            set {
                if ((object.ReferenceEquals(this.DO_UOMField, value) != true)) {
                    this.DO_UOMField = value;
                    this.RaisePropertyChanged("DO_UOM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRMIInterfaceReference.ISRMIInterface")]
    public interface ISRMIInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISRMIInterface/PO_Interface", ReplyAction="http://tempuri.org/ISRMIInterface/PO_InterfaceResponse")]
        AddonProcurement.SRMIInterfaceReference.InterfaceResult[] PO_Interface(AddonProcurement.SRMIInterfaceReference.POinterfacex POdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISRMIInterface/PO_Interface", ReplyAction="http://tempuri.org/ISRMIInterface/PO_InterfaceResponse")]
        System.Threading.Tasks.Task<AddonProcurement.SRMIInterfaceReference.InterfaceResult[]> PO_InterfaceAsync(AddonProcurement.SRMIInterfaceReference.POinterfacex POdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISRMIInterface/DO_Interface", ReplyAction="http://tempuri.org/ISRMIInterface/DO_InterfaceResponse")]
        AddonProcurement.SRMIInterfaceReference.InterfaceResult[] DO_Interface(AddonProcurement.SRMIInterfaceReference.DOInterfacex DOdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISRMIInterface/DO_Interface", ReplyAction="http://tempuri.org/ISRMIInterface/DO_InterfaceResponse")]
        System.Threading.Tasks.Task<AddonProcurement.SRMIInterfaceReference.InterfaceResult[]> DO_InterfaceAsync(AddonProcurement.SRMIInterfaceReference.DOInterfacex DOdata);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISRMIInterfaceChannel : AddonProcurement.SRMIInterfaceReference.ISRMIInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SRMIInterfaceClient : System.ServiceModel.ClientBase<AddonProcurement.SRMIInterfaceReference.ISRMIInterface>, AddonProcurement.SRMIInterfaceReference.ISRMIInterface {
        
        public SRMIInterfaceClient() {
        }
        
        public SRMIInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SRMIInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SRMIInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SRMIInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AddonProcurement.SRMIInterfaceReference.InterfaceResult[] PO_Interface(AddonProcurement.SRMIInterfaceReference.POinterfacex POdata) {
            return base.Channel.PO_Interface(POdata);
        }
        
        public System.Threading.Tasks.Task<AddonProcurement.SRMIInterfaceReference.InterfaceResult[]> PO_InterfaceAsync(AddonProcurement.SRMIInterfaceReference.POinterfacex POdata) {
            return base.Channel.PO_InterfaceAsync(POdata);
        }
        
        public AddonProcurement.SRMIInterfaceReference.InterfaceResult[] DO_Interface(AddonProcurement.SRMIInterfaceReference.DOInterfacex DOdata) {
            return base.Channel.DO_Interface(DOdata);
        }
        
        public System.Threading.Tasks.Task<AddonProcurement.SRMIInterfaceReference.InterfaceResult[]> DO_InterfaceAsync(AddonProcurement.SRMIInterfaceReference.DOInterfacex DOdata) {
            return base.Channel.DO_InterfaceAsync(DOdata);
        }
    }
}
